#!/usr/bin/env python3
"""Generates `recursion_outputs/src/fixtures.cairo`: one test per recursive-tree run, asserting
that the Cairo recomposition of the leaves' preimages reproduces the tree's `program_output`
(the root's raw output words) and, when known, the on-chain `VerificationOutput.output_hash`.

Usage: gen_fixtures.py <out.cairo> <name>:<packed_output.json>:<program_output.json>[:<verifier_output.json>] ...

`verifier_output.json` is the 8-felt output of `scarb execute --output standard` on the root proof
(see verifier_output.sh).
"""
import json
import sys


def walk(node, leaves, leaf_hashes, mv_hashes):
    comp = node["Composite"]
    subs = comp["subtasks"]
    if len(subs) == 1 and "Plain" in subs[0]:
        leaf_hashes.append(tuple(comp["circuit_hash"]))
        leaves.append(subs[0]["Plain"]["output_preimage"])
        return
    mv_hashes.append(tuple(comp["circuit_hash"]))
    for s in subs:
        walk(s, leaves, leaf_hashes, mv_hashes)


def words(ws):
    return "[" + ", ".join(str(w) for w in ws) + "]"


out_path = sys.argv[1]
chunks = [
    "//! GENERATED by spikes/s4/scripts/gen_fixtures.py from the pipeline runs — do not edit.",
    "use crate::tree::{fold_tree, leaf_node, verification_output_hash};",
    "",
]
for spec in sys.argv[2:]:
    parts = spec.split(":")
    name, packed_path, outputs_path = parts[:3]
    verifier_path = parts[3] if len(parts) > 3 else None
    packed = json.load(open(packed_path))
    outputs = json.load(open(outputs_path))
    leaves, leaf_hashes, mv_hashes = [], [], []
    walk(packed, leaves, leaf_hashes, mv_hashes)
    assert len(set(leaf_hashes)) == 1, "all leaves share one leaf circuit hash"
    assert len(set(mv_hashes)) == 1, "all folds share one multiverifier circuit hash"
    lines = [f"/// {len(leaves)} leaves, from {packed_path.split('/')[-2]}/.", "#[test]", f"fn fixture_{name}() {{"]
    lines.append(f"    let leaf_hash: [u32; 8] = {words(leaf_hashes[0])};")
    lines.append(f"    let mv_hash: [u32; 8] = {words(mv_hashes[0])};")
    lines.append("    let leaves = array![")
    for pre in leaves:
        lines.append("        leaf_node(leaf_hash, array![" + ", ".join(pre) + "].span()),")
    lines.append("    ];")
    lines.append("    let root = fold_tree(leaves.span(), mv_hash);")
    lines.append(f"    assert_eq!(root.output, {words(outputs)});")
    if verifier_path:
        vo = json.load(open(verifier_path))
        vo = [int(x, 16) if isinstance(x, str) else int(x) for x in vo]
        lines.append(f"    assert_eq!(verification_output_hash(@root), {words(vo)});")
    lines.append("}")
    chunks.append("\n".join(lines))
    chunks.append("")
open(out_path, "w").write("\n".join(chunks))
print("wrote", out_path)
