#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Line-coverage report for `doom_physics` (PLAN.md §3.1 rule 4, C7).

Same method as `cairo/doom/doom_map/bench/coverage.py`, which this script
imports for its miniature level: `cairo-coverage` 0.5.0 only reads
`snforge` traces, refuses to run without `inlining-strategy = "avoid"`, and
under that flag the real E1M1 data of `doom_map` fails to compile (`Offset
overflow`). So the copy of the `cairo/{crates,doom}` tree gets `doom_map`'s
five-line fixture level in place of E1M1, and `doom_physics`'s test module
is reduced to `src/tests/synthetic.cairo` -- the strip level that module
builds **itself**, out of `geom2d` predicates, with every height rule, line
kind and thing interaction of the crate. The E1M1 vector tests
(`src/tests/e1m1.cairo`) run under `scarb test`, not here.

Production lines only: `src/tests.cairo` and `src/tests/` are excluded.
`cairo-coverage` 0.5.0 emits no `BRF`/`BRH` records, so **branch** coverage
cannot be reported by the tool; line coverage is the proxy, and since
`scarb fmt` puts every branch arm on its own line, a missed arm shows up as a
missed line. The script exits non-zero below 90 % (C7).

Usage: `python3 coverage.py` (needs `snforge` and `cairo-coverage` on PATH).
"""

from __future__ import annotations

import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

CRATE = pathlib.Path(__file__).resolve().parent.parent
CAIRO = CRATE.parent.parent
sys.path.insert(0, str(CAIRO / "doom" / "doom_map" / "bench"))
import coverage as map_coverage  # noqa: E402  (doom_map's script: fixture_level, patch)

SLIM_TESTS = """// SPDX-License-Identifier: GPL-2.0-only
//! GENERATED BY bench/coverage.py -- only the self-contained strip level.
mod synthetic;
"""

EXCLUDED = ("tests.cairo", "/tests/")


def main() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        root = pathlib.Path(tmp) / "cairo"
        root.mkdir()
        ignore = shutil.ignore_patterns("target", "bench", "coverage", "__pycache__")
        shutil.copytree(CAIRO / "crates", root / "crates", ignore=ignore)
        shutil.copytree(CAIRO / "doom", root / "doom", ignore=ignore)
        for group in ("crates", "doom"):
            for package in (root / group).iterdir():
                if package.is_dir() and (package / "Scarb.toml").exists():
                    map_coverage.patch(package)
        level = root / "doom" / "doom_map" / "src" / "levels" / "e1m1.cairo"
        level.write_text(map_coverage.fixture_level())
        work = root / "doom" / CRATE.name
        (work / "src" / "tests.cairo").write_text(SLIM_TESTS)
        for extra in ("e1m1.cairo", "vectors.cairo"):
            (work / "src" / "tests" / extra).unlink()

        proc = subprocess.run(
            ["snforge", "test", "--coverage"], cwd=work, capture_output=True, text=True
        )
        if proc.returncode != 0:
            print(proc.stdout[-4000:], proc.stderr[-2000:], sep="\n")
            return 1
        tests = re.search(r"Tests: (\d+) passed", proc.stdout)

        lcov = (work / "coverage" / "coverage.lcov").read_text()
        source: pathlib.Path | None = None
        skip = False
        hit = total = 0
        uncovered: list[str] = []
        per_file: dict[str, list[int]] = {}
        for line in lcov.splitlines():
            if line.startswith("SF:"):
                source = pathlib.Path(line[3:])
                skip = str(work) not in str(source) or any(m in str(source) for m in EXCLUDED)
                continue
            if skip:
                continue
            match = re.match(r"^DA:(\d+),(\d+)$", line)
            if match and source is not None:
                total += 1
                counts = per_file.setdefault(source.name, [0, 0])
                counts[1] += 1
                if int(match.group(2)) > 0:
                    hit += 1
                    counts[0] += 1
                else:
                    uncovered.append("%s:%s" % (source.name, match.group(1)))

    percent = 100.0 * hit / total if total else 0.0
    print(
        "%s: %s test(s), production lines %d/%d = %.1f%%"
        % (CRATE.name, tests.group(1) if tests else "?", hit, total, percent)
    )
    for name, (h, t) in sorted(per_file.items()):
        print("  %-18s %4d/%4d" % (name, h, t))
    if uncovered:
        print("uncovered: " + ", ".join(uncovered))
    return 0 if percent >= 90.0 else 1


if __name__ == "__main__":
    sys.exit(main())
