/**
 * Vanilla Doom linedef special-type numbers: short mechanical descriptions,
 * derived from the well-known public "Doom linedef types" reference tables
 * (Doom Wiki / Unofficial Doom Specs), paraphrased here rather than quoted.
 * Only used to make `REPORT-e1m1.md` readable; gameplay code (Phase 1) will
 * implement the actual behaviors it needs based on what the report finds.
 */
export type LinedefCategory =
  | "door"
  | "floor"
  | "ceiling"
  | "lift" // "plat" in the original source: platforms/lifts
  | "stairs"
  | "exit"
  | "teleport"
  | "light"
  | "crusher"
  | "scroll"
  | "other";

export interface LinedefSpecialInfo {
  name: string;
  category: LinedefCategory;
}

const T: Record<number, LinedefSpecialInfo> = {
  1: { name: "Door: open-wait-close (manual, slow)", category: "door" },
  2: { name: "Door: open and stay (walk, once)", category: "door" },
  3: { name: "Door: close and stay (walk, once)", category: "door" },
  4: { name: "Door: open-wait-close (walk, monsters can trigger)", category: "door" },
  5: { name: "Floor: raise to lowest adjacent ceiling (walk)", category: "floor" },
  6: { name: "Ceiling: crush and raise, fast (walk, once)", category: "crusher" },
  7: { name: "Stairs: build 8 units up (walk, once)", category: "stairs" },
  8: { name: "Stairs: build 8 units up (walk)", category: "stairs" },
  9: { name: "Floor: donut (raises the donut ring around a pillar) (walk, once)", category: "floor" },
  10: { name: "Lift: down-wait-up-stay, fast (walk)", category: "lift" },
  11: { name: "Exit: normal end of level (switch, once)", category: "exit" },
  12: { name: "Light: set to the brightest adjacent sector (walk)", category: "light" },
  13: { name: "Light: set to maximum (255) (walk)", category: "light" },
  14: { name: "Lift: raise 32 and change texture (walk, once)", category: "lift" },
  15: { name: "Lift: raise 24 and change texture (walk, once)", category: "lift" },
  16: { name: "Door: close 30, then open (walk, once)", category: "door" },
  17: { name: "Light: flickering/strobe (walk)", category: "light" },
  18: { name: "Floor: raise to next highest floor (walk, once)", category: "floor" },
  19: { name: "Floor: lower to highest adjacent floor (walk, once)", category: "floor" },
  20: { name: "Lift: raise to nearest floor and change texture (walk)", category: "lift" },
  21: { name: "Lift: down-wait-up-stay (walk)", category: "lift" },
  22: { name: "Floor: raise to nearest floor and change texture (walk)", category: "floor" },
  23: { name: "Floor: lower to lowest adjacent floor (walk, once)", category: "floor" },
  24: { name: "Floor: raise to lowest adjacent ceiling (shoot/hitscan, once)", category: "floor" },
  25: { name: "Ceiling: crush and raise (walk)", category: "crusher" },
  26: { name: "Door: open-wait-close, needs blue key (walk, once)", category: "door" },
  27: { name: "Door: open-wait-close, needs yellow key (walk, once)", category: "door" },
  28: { name: "Door: open-wait-close, needs red key (walk, once)", category: "door" },
  29: { name: "Door: open-wait-close, slow (walk, once)", category: "door" },
  30: { name: "Floor: raise by the shortest lower texture height (walk, once)", category: "floor" },
  31: { name: "Door: open and stay (walk, once)", category: "door" },
  32: { name: "Door: open and stay, needs blue key (walk, once)", category: "door" },
  33: { name: "Door: open and stay, needs red key (walk, once)", category: "door" },
  34: { name: "Door: open and stay, needs yellow key (walk, once)", category: "door" },
  35: { name: "Light: set to a specific low level (walk)", category: "light" },
  36: { name: "Floor: lower to 8 above highest floor, fast (walk, once)", category: "floor" },
  37: { name: "Floor: lower to lowest floor and change texture/type (walk, once)", category: "floor" },
  38: { name: "Floor: lower to lowest adjacent floor (walk, once)", category: "floor" },
  39: { name: "Teleport (walk, once)", category: "teleport" },
  40: { name: "Ceiling: raise to highest adjacent ceiling (walk, once)", category: "ceiling" },
  41: { name: "Ceiling: lower to floor (walk, once)", category: "ceiling" },
  42: { name: "Door: close (switch, once)", category: "door" },
  43: { name: "Ceiling: lower to floor (walk)", category: "ceiling" },
  44: { name: "Ceiling: lower to 8 above floor, crushing (walk, once)", category: "ceiling" },
  45: { name: "Floor: lower to highest adjacent floor (switch)", category: "floor" },
  46: { name: "Door: open (shoot/hitscan, repeatable)", category: "door" },
  47: { name: "Floor: raise to nearest floor and change texture (switch, once)", category: "floor" },
  48: { name: "Scroll wall texture left (always active)", category: "scroll" },
  49: { name: "Ceiling: crush and raise (switch, once)", category: "crusher" },
  50: { name: "Door: close (switch, once)", category: "door" },
  51: { name: "Exit: secret level (switch, once)", category: "exit" },
  52: { name: "Exit: normal end of level (walk, once)", category: "exit" },
  53: { name: "Lift: perpetual up/down motion (walk)", category: "lift" },
  54: { name: "Lift: stop perpetual motion (walk)", category: "lift" },
  55: { name: "Floor: raise, crushing (switch, once)", category: "floor" },
  56: { name: "Floor: raise, crushing (walk, once)", category: "floor" },
  57: { name: "Ceiling: stop crusher (walk)", category: "crusher" },
  58: { name: "Floor: raise by 24 (walk, once)", category: "floor" },
  59: { name: "Floor: raise by 24 and change texture (walk, once)", category: "floor" },
  60: { name: "Floor: lower to lowest adjacent floor (switch, once)", category: "floor" },
  61: { name: "Door: open and stay (switch)", category: "door" },
  62: { name: "Lift: down-wait-up-stay (switch)", category: "lift" },
  63: { name: "Door: open-wait-close (switch, once)", category: "door" },
  64: { name: "Floor: raise to lowest adjacent ceiling (switch)", category: "floor" },
  65: { name: "Floor: raise, crushing (switch)", category: "floor" },
  66: { name: "Lift: raise 24 and change texture (switch, once)", category: "lift" },
  67: { name: "Lift: raise 32 and change texture (switch, once)", category: "lift" },
  68: { name: "Lift: raise to nearest floor and change texture (switch)", category: "lift" },
  69: { name: "Floor: raise to next highest floor (switch)", category: "floor" },
  70: { name: "Floor: lower to 8 above highest floor, fast (switch, once)", category: "floor" },
  71: { name: "Floor: lower to 8 above highest floor, fast (switch)", category: "floor" },
  72: { name: "Ceiling: lower to floor, crushing (walk)", category: "ceiling" },
  73: { name: "Ceiling: crush and raise, slow (walk, once)", category: "crusher" },
  74: { name: "Ceiling: stop crusher (switch, once)", category: "crusher" },
  75: { name: "Door: close (walk, repeatable)", category: "door" },
  76: { name: "Door: close 30, then open (walk, once)", category: "door" },
  77: { name: "Ceiling: crush and raise, fast (walk, repeatable)", category: "crusher" },
  79: { name: "Light: set to a specific low level (switch, repeatable)", category: "light" },
  80: { name: "Light: set to the brightest adjacent sector (walk, repeatable)", category: "light" },
  81: { name: "Light: set to maximum (255) (switch, repeatable)", category: "light" },
  82: { name: "Floor: lower to lowest adjacent floor (walk, repeatable)", category: "floor" },
  83: { name: "Floor: lower to lowest adjacent floor (walk, repeatable)", category: "floor" },
  84: { name: "Floor: lower to lowest floor and change texture (walk, repeatable)", category: "floor" },
  86: { name: "Door: open and stay (walk, repeatable)", category: "door" },
  87: { name: "Lift: perpetual up/down motion (switch)", category: "lift" },
  88: { name: "Lift: down-wait-up-stay (walk, repeatable, monsters can trigger)", category: "lift" },
  89: { name: "Lift: raise to nearest floor and change texture (walk, repeatable)", category: "lift" },
  90: { name: "Door: open-wait-close (walk, repeatable)", category: "door" },
  91: { name: "Floor: raise to lowest adjacent ceiling (walk, repeatable)", category: "floor" },
  92: { name: "Floor: raise by 24 (walk, repeatable)", category: "floor" },
  93: { name: "Floor: raise by 24 and change texture (walk, repeatable)", category: "floor" },
  94: { name: "Floor: raise, crushing (walk, repeatable)", category: "floor" },
  95: { name: "Lift: raise to nearest floor and change texture (switch, repeatable)", category: "lift" },
  96: { name: "Floor: raise by the shortest lower texture height (walk, repeatable)", category: "floor" },
  97: { name: "Teleport (walk, repeatable)", category: "teleport" },
  98: { name: "Floor: lower to 8 above highest floor, fast (walk, repeatable)", category: "floor" },
  99: { name: "Door: open and stay, needs blue key, fast (switch, once)", category: "door" },
  100: { name: "Stairs: build 16 units up, fast (walk, once)", category: "stairs" },
  101: { name: "Floor: raise to lowest adjacent ceiling (switch)", category: "floor" },
  102: { name: "Floor: lower to highest adjacent floor (switch)", category: "floor" },
  103: { name: "Door: open and stay (switch, once)", category: "door" },
  104: { name: "Light: set to the darkest adjacent sector (walk)", category: "light" },
  105: { name: "Door: open-wait-close, fast (walk, repeatable)", category: "door" },
  106: { name: "Door: open and stay, fast (walk, once)", category: "door" },
  107: { name: "Door: close, fast (walk, once)", category: "door" },
  108: { name: "Door: open-wait-close, fast (walk, once)", category: "door" },
  109: { name: "Door: open-wait-close, fast (switch, once)", category: "door" },
  110: { name: "Door: close, fast (switch, once)", category: "door" },
  111: { name: "Door: open-wait-close, fast (walk, once)", category: "door" },
  112: { name: "Door: open-wait-close, fast (walk, repeatable)", category: "door" },
  113: { name: "Door: open and stay, fast (walk, repeatable)", category: "door" },
  114: { name: "Door: open-wait-close, fast (switch, repeatable)", category: "door" },
  115: { name: "Door: open and stay, fast (switch, once)", category: "door" },
  116: { name: "Door: close, fast (switch, repeatable)", category: "door" },
  117: { name: "Door: open-wait-close, fast (switch, repeatable)", category: "door" },
  118: { name: "Door: open, fast (switch, once)", category: "door" },
  119: { name: "Floor: raise to nearest floor (walk, once)", category: "floor" },
  120: { name: "Lift: down-wait-up-stay, fast (walk, once)", category: "lift" },
  121: { name: "Lift: down-wait-up-stay, fast (walk, repeatable)", category: "lift" },
  122: { name: "Lift: down-wait-up-stay, fast (switch, once)", category: "lift" },
  123: { name: "Lift: down-wait-up-stay, fast (switch, repeatable)", category: "lift" },
  124: { name: "Exit: secret level (switch, once)", category: "exit" },
  125: { name: "Teleport, monsters only (walk, once)", category: "teleport" },
  126: { name: "Teleport, monsters only (walk, repeatable)", category: "teleport" },
  127: { name: "Stairs: build 16 units up, fast (switch, once)", category: "stairs" },
  128: { name: "Floor: raise to nearest floor and change texture (walk, repeatable)", category: "floor" },
  129: { name: "Floor: raise to nearest floor and change texture, monsters only (walk, repeatable)", category: "floor" },
  130: { name: "Floor: raise to nearest floor (walk, repeatable)", category: "floor" },
  131: { name: "Floor: raise to nearest floor (switch, once)", category: "floor" },
  132: { name: "Floor: raise to nearest floor (switch, repeatable)", category: "floor" },
  133: { name: "Door: open and stay, needs blue key, fast (switch, once)", category: "door" },
  134: { name: "Door: open and stay, needs red key, fast (switch, once)", category: "door" },
  135: { name: "Door: open and stay, needs red key, fast (switch, repeatable)", category: "door" },
  136: { name: "Door: open and stay, needs yellow key, fast (switch, repeatable)", category: "door" },
  137: { name: "Door: open and stay, needs yellow key, fast (switch, once)", category: "door" },
  138: { name: "Light: set to maximum (255) (switch, repeatable)", category: "light" },
  139: { name: "Light: set to a specific low level (switch, repeatable)", category: "light" },
  140: { name: "Floor: raise by 512 (switch, once)", category: "floor" },
  141: { name: "Ceiling: crush and raise, silent (walk, once)", category: "crusher" },
};

export function linedefSpecialInfo(specialType: number): LinedefSpecialInfo {
  if (specialType === 0) return { name: "No special", category: "other" };
  return T[specialType] ?? { name: `Unknown/unmapped linedef special ${specialType}`, category: "other" };
}
