// SPDX-License-Identifier: Apache-2.0
//! Binary Angle Measurement: Doom's 32-bit angles, the `finesine` /
//! `finecosine` / `tantoangle` tables, and `point_to_angle`.
//!
//! # Representation
//!
//! [`Angle`] is a `u32` in which the whole range is one turn, so angle
//! arithmetic is modulo 2^32 and **wraps by construction** — the property
//! Doom relies on everywhere. `u32` addition panics on overflow in Cairo,
//! and a panic makes a segment unprovable (RISKS R4), so [`add`] / [`sub`]
//! go through the wrap explicitly.
//!
//! # Tables
//!
//! `finesine` has 8 192 entries in Doom (10 240 with the `finecosine`
//! overlap). This crate stores **one quarter wave of 2 048 non-negative
//! magnitudes** ([`tables::FINESINE_Q`]) and rebuilds every entry with two
//! comparisons, because since S0 the bootloader re-hashes the program each
//! segment at 14.7 steps per word: the 8 192 felts saved are worth ~1 200
//! steps/tic amortized at K = 100, against ~15 steps per call to fold
//! (S1 §5.9, §7). The same arbitrage *rejects* bit-packing several 16-bit
//! magnitudes per felt: it would save ~1 500 more felts (~220 steps/tic)
//! but cost ~50 extra steps on each of the ~20 lookups of a tic (~1 000
//! steps/tic).
//!
//! `finecosine[i] == finesine[i + 2048]`, so there is no second table
//! either; [`cosine`] only shifts the index.
//!
//! Tables are generated by `scripts/gen_tables.py` from closed-form formulas
//! (clean-room). Doom's own tables, computed with 1990s floating point,
//! differ from them in 33 of 10 240 sine entries by exactly one unit in the
//! last place and in `tantoangle` by at most 16 BAM (8.4e-8 degrees * 16);
//! the tests pin both bounds against sampled reference values.

use fixed::{BIAS, Fixed};
use tables::{FINESINE_Q, TANTOANGLE};

pub mod tables;

/// A Doom angle: the full `u32` range is one turn (2^32 BAM).
pub type Angle = u32;

pub const ANG0: Angle = 0;
pub const ANG45: Angle = 0x20000000;
pub const ANG90: Angle = 0x40000000;
pub const ANG180: Angle = 0x80000000;
pub const ANG270: Angle = 0xC0000000;
/// One full turn, as the modulus of angle arithmetic (2^32).
pub const ANG_TURN: u64 = 0x100000000;

/// Number of entries of Doom's `finesine` over a full turn.
pub const FINEANGLES: u32 = 8192;
/// Largest valid fine index.
pub const FINEMASK: u32 = 8191;
/// A quarter turn in fine indices.
pub const FINE_QUARTER: u32 = 2048;
/// `2^32 / 8192`: the shift from an [`Angle`] to a fine index.
pub const ANGLETOFINESHIFT: u32 = 0x80000;

/// Largest slope index accepted by [`tantoangle`] (Doom's `SLOPERANGE`).
pub const SLOPERANGE: u32 = 2048;

// ---------------------------------------------------------------------------
// Angle arithmetic
// ---------------------------------------------------------------------------

/// `a + b` modulo a full turn.
///
/// Stays inside `u32`: widening to `u64` and reducing costs 16 steps, the
/// three `u32` operations below cost 10.
///
/// **Measured: 10 steps, 2 range checks.**
pub fn add(a: Angle, b: Angle) -> Angle {
    let limit = 0xFFFFFFFF - b;
    if a > limit {
        // a + b >= 2^32: subtract the turn without ever leaving u32.
        a - limit - 1
    } else {
        a + b
    }
}

/// `a - b` modulo a full turn.
///
/// **Measured: 11 steps, 2 range checks.**
pub fn sub(a: Angle, b: Angle) -> Angle {
    if a >= b {
        a - b
    } else {
        let d: u64 = ANG_TURN + a.into() - b.into();
        d.try_into().unwrap()
    }
}

/// `-a` modulo a full turn.
///
/// **Measured: 10 steps, 2 range checks.**
pub fn neg(a: Angle) -> Angle {
    if a == 0 {
        0
    } else {
        let d: u64 = ANG_TURN - a.into();
        d.try_into().unwrap()
    }
}

/// Reduce a felt that accumulated several angle increments back into one
/// turn. Cheaper than wrapping after every increment when an angle is built
/// from a sum of terms: keep the sum in the field and reduce **once**
/// (S1 §7 recommends one reduction per tic).
///
/// `x` must be a non-negative felt below 2^71.
///
/// **Measured: 17 steps, 6 range checks.**
pub fn reduce(x: felt252) -> Angle {
    let u: u128 = x.try_into().unwrap();
    (u % 0x100000000).try_into().unwrap()
}

// ---------------------------------------------------------------------------
// Table lookups
// ---------------------------------------------------------------------------

/// Fine table index of an angle (Doom's `angle >> ANGLETOFINESHIFT`).
/// Always in `[0, 8192)`.
///
/// **Measured: 8 steps, 3 range checks.**
pub fn angle_to_fine_index(a: Angle) -> u32 {
    a / ANGLETOFINESHIFT
}

/// `finesine[idx]` for `idx` in `[0, 8192)`, rebuilt from the quarter wave.
///
/// Panics if `idx >= 8192`: callers get their index from
/// [`angle_to_fine_index`], which cannot produce one.
///
/// **Measured: 45 steps, 4 range checks** (two `u32` comparisons, one
/// `Span` index at S1's constant 11 steps, one re-encoding).
pub fn finesine(idx: u32) -> Fixed {
    let (negative, half) = if idx >= 4096 {
        (true, idx - 4096)
    } else {
        (false, idx)
    };
    let q = if half >= FINE_QUARTER {
        4095 - half
    } else {
        half
    };
    let m = *FINESINE_Q.span().at(q);
    if negative {
        Fixed { enc: BIAS - m }
    } else {
        Fixed { enc: BIAS + m }
    }
}

/// `finecosine[idx] == finesine[idx + 2048]`, for `idx` in `[0, 8192)`.
///
/// **Measured: 58 steps, 7 range checks.**
pub fn finecosine(idx: u32) -> Fixed {
    let shifted = idx + FINE_QUARTER;
    let wrapped = if shifted >= FINEANGLES {
        shifted - FINEANGLES
    } else {
        shifted
    };
    finesine(wrapped)
}

/// `sin(a)`.
///
/// **Measured: 51 steps, 6 range checks.**
pub fn sine(a: Angle) -> Fixed {
    finesine(angle_to_fine_index(a))
}

/// `cos(a)`.
///
/// **Measured: 64 steps, 9 range checks.**
pub fn cosine(a: Angle) -> Fixed {
    finecosine(angle_to_fine_index(a))
}

/// `(sin(a), cos(a))` with a single index reduction.
///
/// S1 §7 expected the pair to be worth ~14 steps over two separate calls,
/// because the `u32` division of [`angle_to_fine_index`] would be paid once.
/// Measured, the saving is only **6 steps** (109 against 51 + 64): the index
/// reduction is 8 steps, not 30, because `angle >> 19` on a `u32` needs a
/// single division and no mask. The pair is kept for the call sites that
/// want both, but it is not the optimization S1 thought it was.
///
/// **Measured: 109 steps, 12 range checks.**
pub fn sin_cos(a: Angle) -> (Fixed, Fixed) {
    let i = angle_to_fine_index(a);
    (finesine(i), finecosine(i))
}

/// `tantoangle[slope]` for `slope` in `[0, 2048]`: the angle whose tangent
/// is `slope / 2048`, in `[0, ANG45]`.
///
/// **Measured: 16 steps, 3 range checks.**
pub fn tantoangle(slope: u32) -> Angle {
    let v = *TANTOANGLE.span().at(slope);
    v.try_into().unwrap()
}

// ---------------------------------------------------------------------------
// point_to_angle
// ---------------------------------------------------------------------------

/// Doom's `SlopeDiv`: `min(2048, (num << 3) / (den >> 8))`, on two
/// non-negative raw magnitudes below 2^32. Returns a slope index usable
/// with [`tantoangle`].
///
/// **Measured: 45 steps, 12 range checks.**
pub fn slope_div(num: felt252, den: felt252) -> u32 {
    let d: u128 = den.try_into().unwrap();
    if d < 512 {
        return SLOPERANGE;
    }
    let n: u128 = (num * 8).try_into().unwrap();
    let ans = n / (d / 256);
    if ans > 2048 {
        SLOPERANGE
    } else {
        ans.try_into().unwrap()
    }
}

/// Angle of the vector `(dx, dy)`, i.e. Doom's `R_PointToAngle2`: the plane
/// is folded into its first octant, the slope is divided down to a table
/// index and read from `tantoangle`, and the octant is folded back.
///
/// `(0, 0)` returns `ANG0`, like the original.
///
/// **Measured: 118 steps, 22 range checks** (S1 §5.6 measured 138 for the
/// same function in the spike prototype).
pub fn point_to_angle(dx: Fixed, dy: Fixed) -> Angle {
    let (x_neg, x) = fixed::split(dx);
    let (y_neg, y) = fixed::split(dy);
    if x == 0 && y == 0 {
        return ANG0;
    }
    // Doom compares the two magnitudes with `x > y`: one felt_ge, negated.
    let x_bigger = !fixed::felt_ge(y, x);
    if !x_neg {
        if !y_neg {
            // First octant pair: [0, ANG90).
            if x_bigger {
                tantoangle(slope_div(y, x))
            } else {
                ANG90 - 1 - tantoangle(slope_div(x, y))
            }
        } else {
            // Fourth quadrant: (ANG270, ANG360).
            if x_bigger {
                neg(tantoangle(slope_div(y, x)))
            } else {
                ANG270 + tantoangle(slope_div(x, y))
            }
        }
    } else {
        if !y_neg {
            // Second quadrant: (ANG90, ANG180].
            if x_bigger {
                ANG180 - 1 - tantoangle(slope_div(y, x))
            } else {
                ANG90 + tantoangle(slope_div(x, y))
            }
        } else {
            // Third quadrant: (ANG180, ANG270).
            if x_bigger {
                ANG180 + tantoangle(slope_div(y, x))
            } else {
                ANG270 - 1 - tantoangle(slope_div(x, y))
            }
        }
    }
}

/// Angle from `(x1, y1)` to `(x2, y2)` (Doom's `R_PointToAngle2` signature).
///
/// **Measured: 122 steps, 22 range checks.**
pub fn point_to_angle2(x1: Fixed, y1: Fixed, x2: Fixed, y2: Fixed) -> Angle {
    point_to_angle(fixed::sub(x2, x1), fixed::sub(y2, y1))
}

#[cfg(test)]
mod tests;
