// SPDX-License-Identifier: Apache-2.0
//! Unit tests: wrap-around, table reference values against Doom's own
//! `finesine`/`tantoangle`, `point_to_angle` against 1 000 generated
//! vectors, symmetries and edge cases.
//!
//! Vectors are generated by `scripts/gen_tables.py --tables-c <path>`; see
//! `tests/vectors.cairo` for what they are and how far Doom's 1990s tables
//! drift from the closed-form formulas.

mod vectors;
use fixed::{BIAS, FRACUNIT_RAW, Fixed, felt_ge, from_raw, from_units};
use vectors::{
    FINESINE_MAX_DELTA, PTA_ANGLE, PTA_DX_ENC, PTA_DY_ENC, PTA_MAX_DELTA, SIN_DOOM_OFFSET,
    SIN_INDEX, TANTOANGLE_MAX_DELTA, TAN_DOOM, TAN_INDEX,
};
use super::tables::{FINESINE_Q, TANTOANGLE};
use super::{
    ANG0, ANG180, ANG270, ANG45, ANG90, ANG_TURN, Angle, FINEANGLES, FINE_QUARTER, SLOPERANGE, add,
    angle_to_fine_index, cosine, finecosine, finesine, neg, point_to_angle, point_to_angle2, reduce,
    sin_cos, sine, slope_div, sub, tantoangle,
};

/// `|a - b|` on raw sine magnitudes, both known to be small.
fn abs_delta(a: felt252, b: felt252) -> felt252 {
    if felt_ge(a, b) {
        a - b
    } else {
        b - a
    }
}

/// Shortest distance between two BAM angles, as a felt.
fn angular_delta(a: Angle, b: Angle) -> felt252 {
    let d = sub(a, b);
    let e = sub(b, a);
    if d <= e {
        d.into()
    } else {
        e.into()
    }
}

// ---------------------------------------------------------------------------
// Wrap-around
// ---------------------------------------------------------------------------

#[test]
fn test_add_wraps_at_a_full_turn() {
    assert(add(ANG270, ANG90) == ANG0, '270+90 wraps to 0');
    assert(add(0xFFFFFFFF, 1) == 0, 'max+1 wraps to 0');
    assert(add(0xFFFFFFFF, 2) == 1, 'max+2 wraps to 1');
    assert(add(ANG0, 0xFFFFFFFF) == 0xFFFFFFFF, 'identity');
    assert(add(ANG180, ANG180) == ANG0, 'half turns cancel');
}

#[test]
fn test_sub_wraps_below_zero() {
    assert(sub(0, 1) == 0xFFFFFFFF, '0-1 wraps');
    assert(sub(ANG90, ANG90) == 0, 'self sub');
    assert(sub(ANG0, ANG90) == ANG270, '0-90 is 270');
}

#[test]
fn test_neg_is_the_additive_inverse() {
    assert(neg(0) == 0, '-0 is 0');
    assert(neg(ANG90) == ANG270, '-90 is 270');
    assert(add(ANG45, neg(ANG45)) == 0, 'a + (-a) == 0');
    assert(neg(neg(0xDEADBEEF)) == 0xDEADBEEF, 'double negation');
}

#[test]
fn test_add_and_sub_are_inverses_over_a_deterministic_sweep() {
    let mut i: u32 = 0;
    let mut a: u32 = 0x13579BDF;
    while i != 64 {
        let b: u32 = a / 3 + 0x01234567;
        assert(sub(add(a, b), b) == a, 'add then sub');
        assert(add(sub(a, b), b) == a, 'sub then add');
        assert(add(a, b) == add(b, a), 'add commutes');
        a = add(a, 0x0A0B0C0D);
        i += 1;
    }
}

#[test]
fn test_reduce_folds_a_felt_sum_into_one_turn() {
    assert(reduce(0) == 0, 'reduce 0');
    assert(reduce(ANG90.into()) == ANG90, 'reduce identity');
    // Three quarter turns plus a full turn.
    let sum: felt252 = ANG_TURN.into() + ANG270.into();
    assert(reduce(sum) == ANG270, 'reduce past one turn');
    let many: felt252 = 5 * ANG_TURN.into() + 12345;
    assert(reduce(many) == 12345, 'reduce many turns');
}

// ---------------------------------------------------------------------------
// Fine index and table structure
// ---------------------------------------------------------------------------

#[test]
fn test_angle_to_fine_index_covers_the_table_exactly() {
    assert(angle_to_fine_index(ANG0) == 0, 'index of 0');
    assert(angle_to_fine_index(ANG90) == 2048, 'index of 90');
    assert(angle_to_fine_index(ANG180) == 4096, 'index of 180');
    assert(angle_to_fine_index(ANG270) == 6144, 'index of 270');
    assert(angle_to_fine_index(0xFFFFFFFF) == 8191, 'index of max');
    // Monotone and never out of range.
    let mut i: u32 = 0;
    let mut a: u32 = 0;
    while i != 256 {
        let idx = angle_to_fine_index(a);
        assert(idx < FINEANGLES, 'index in range');
        a = add(a, 0x00FEDCBA);
        i += 1;
    }
}

#[test]
fn test_quarter_wave_table_shape() {
    let q = FINESINE_Q.span();
    assert(q.len() == FINE_QUARTER, 'quarter wave is 2048 long');
    assert(*q.at(0) == 25, 'first entry is 25');
    assert(*q.at(2047) == 65535, 'last entry saturates');
    // Monotone non-decreasing over the quarter wave.
    let mut i: u32 = 1;
    while i != 2048 {
        assert(felt_ge(*q.at(i), *q.at(i - 1)), 'quarter wave is monotone');
        i += 1;
    }
    let t = TANTOANGLE.span();
    assert(t.len() == 2049, 'tantoangle is 2049 long');
    assert(*t.at(0) == 0, 'tan(0) is 0');
    assert(*t.at(2048) == ANG45.into(), 'tan(1) is 45 degrees');
}

#[test]
fn test_sine_symmetries_over_the_whole_wave() {
    let mut i: u32 = 0;
    while i != 4096 {
        // sin(x + 180) == -sin(x)
        let s = finesine(i);
        let o = finesine(i + 4096);
        assert(s.enc + o.enc == BIAS + BIAS, 'antisymmetric half turn');
        // sin(x) == sin(180 - x) within the first half
        if i < 2048 {
            assert(finesine(4095 - i) == s, 'mirror around 90 degrees');
        }
        i += 1;
    }
}

#[test]
fn test_sine_cosine_anchor_values() {
    assert(finesine(0).enc == BIAS + 25, 'sin(0) is the half step');
    assert(finesine(2047) == from_raw(65535), 'sin(90) saturates at 65535');
    assert(finesine(4095) == from_raw(25), 'sin(180-) is the half step');
    assert(finesine(4096) == from_raw(-25), 'sin(180+) is negative');
    assert(finesine(6143) == from_raw(-65535), 'sin(270) is -1');
    assert(finecosine(0) == finesine(2048), 'cos is sin shifted');
    assert(finecosine(2048) == finesine(4096), 'cos(90) is negative');
    assert(finecosine(6144) == finesine(0), 'cos wraps');
    assert(sine(ANG90) == from_raw(65535), 'sine(ANG90)');
    assert(cosine(ANG0) == from_raw(65535), 'cosine(ANG0)');
    assert(cosine(ANG180) == from_raw(-65535), 'cosine(ANG180)');
}

#[test]
fn test_sin_cos_pair_matches_the_separate_lookups() {
    let mut i: u32 = 0;
    let mut a: u32 = 0;
    while i != 128 {
        let (s, c) = sin_cos(a);
        assert(s == sine(a), 'sin matches');
        assert(c == cosine(a), 'cos matches');
        a = add(a, 0x02468ACE);
        i += 1;
    }
}

#[test]
fn test_sin_cos_shared_fold_every_fine_index_and_low_bits() {
    // The old independent sine/cosine paths are the oracle. Check both
    // ends of every fine-angle bucket, including u32::MAX in the last.
    let mut index: u32 = 0;
    while index != 8192 {
        let first = index * 524288;
        let last = first + 524287;
        let (s0, c0) = sin_cos(first);
        let (s1, c1) = sin_cos(last);
        assert(s0 == sine(first) && c0 == cosine(first), 'first bucket angle');
        assert(s1 == sine(last) && c1 == cosine(last), 'last bucket angle');
        index += 1;
    }
}

#[test]
fn test_sine_squared_plus_cosine_squared_is_one() {
    // Property: the table is a real sine to within its own resolution.
    // Each of s and c is truncated by up to 1 ulp and `mul` floors, so
    // s^2 + c^2 can sit up to ~6 ulp below FRACUNIT; 8 is the bound.
    let mut i: u32 = 0;
    let mut a: u32 = 12345;
    while i != 64 {
        let (s, c) = sin_cos(a);
        let ss = fixed::mul(s, s);
        let cc = fixed::mul(c, c);
        let one = fixed::add(ss, cc);
        let d = abs_delta(one.enc, BIAS + FRACUNIT_RAW);
        assert(!felt_ge(d, 9), 'sin^2 + cos^2 == 1');
        a = add(a, 0x01234567);
        i += 1;
    }
}

// ---------------------------------------------------------------------------
// Reference values from Doom's own tables
// ---------------------------------------------------------------------------

#[test]
fn test_finesine_matches_doom_within_one_ulp() {
    let idx = SIN_INDEX.span();
    let doom = SIN_DOOM_OFFSET.span();
    assert(idx.len() == doom.len(), 'vector lengths agree');
    assert(idx.len() > 100, 'enough samples');
    let mut k: u32 = 0;
    while k != idx.len() {
        let i: u32 = (*idx.at(k)).try_into().unwrap();
        // The vector is offset by +65536 to stay non-negative.
        let expected = *doom.at(k) - 65536;
        let got = fixed::to_raw(finesine(i));
        let d = abs_delta(got + 65536, expected + 65536);
        assert(!felt_ge(d, FINESINE_MAX_DELTA + 1), 'finesine within 1 ulp');
        k += 1;
    }
}

#[test]
fn test_tantoangle_matches_doom_within_the_recorded_bound() {
    let idx = TAN_INDEX.span();
    let doom = TAN_DOOM.span();
    assert(idx.len() == doom.len(), 'vector lengths agree');
    let mut k: u32 = 0;
    while k != idx.len() {
        let i: u32 = (*idx.at(k)).try_into().unwrap();
        let got: felt252 = tantoangle(i).into();
        let d = abs_delta(got, *doom.at(k));
        assert(!felt_ge(d, TANTOANGLE_MAX_DELTA + 1), 'tantoangle within bound');
        k += 1;
    }
    // The two anchors must be exact.
    assert(tantoangle(0) == 0, 'tantoangle(0) exact');
    assert(tantoangle(2048) == ANG45, 'tantoangle(2048) exact');
}

// ---------------------------------------------------------------------------
// point_to_angle
// ---------------------------------------------------------------------------

#[test]
fn test_point_to_angle_matches_1000_generated_vectors() {
    let dx = PTA_DX_ENC.span();
    let dy = PTA_DY_ENC.span();
    let ang = PTA_ANGLE.span();
    assert(dx.len() == 1000 && dy.len() == 1000 && ang.len() == 1000, '1000 vectors');
    let mut i: u32 = 0;
    while i != 1000 {
        let got: felt252 = point_to_angle(Fixed { enc: *dx.at(i) }, Fixed { enc: *dy.at(i) })
            .into();
        assert(got == *ang.at(i), 'point_to_angle matches');
        i += 1;
    }
}

#[test]
fn test_point_to_angle_cardinal_and_diagonal_directions() {
    let u = from_units(64);
    let mu = from_units(-64);
    let z = from_units(0);
    assert(point_to_angle(z, z) == ANG0, 'degenerate is 0');
    assert(point_to_angle(u, z) == ANG0, 'east');
    assert(point_to_angle(z, u) == ANG90 - 1, 'north');
    assert(point_to_angle(mu, z) == ANG180 - 1, 'west');
    assert(point_to_angle(z, mu) == ANG270, 'south');
    // The four diagonals land within a table step of the exact 45 degrees.
    assert(!felt_ge(angular_delta(point_to_angle(u, u), ANG45), 300000), 'north-east');
    assert(!felt_ge(angular_delta(point_to_angle(mu, u), ANG90 + ANG45), 300000), 'north-west');
    assert(!felt_ge(angular_delta(point_to_angle(mu, mu), ANG180 + ANG45), 300000), 'south-west');
    assert(!felt_ge(angular_delta(point_to_angle(u, mu), ANG270 + ANG45), 300000), 'south-east');
}

#[test]
fn test_point_to_angle_is_invariant_under_positive_scaling() {
    // Only the direction matters (up to the table's own resolution).
    let a = point_to_angle(from_units(3), from_units(7));
    let b = point_to_angle(from_units(300), from_units(700));
    assert(!felt_ge(angular_delta(a, b), PTA_MAX_DELTA), 'scale invariant');
}

#[test]
fn test_point_to_angle_negation_turns_by_180_degrees() {
    let mut i: u32 = 0;
    let mut seed: u64 = 987654;
    while i != 32 {
        // Deterministic LCG folded into +/- 2^25 raw units, well inside the
        // `fixed` domain.
        seed = (seed * 1664525 + 1013904223) % 0x100000000;
        let sx: felt252 = (seed % 0x4000000).into();
        seed = (seed * 1664525 + 1013904223) % 0x100000000;
        let sy: felt252 = (seed % 0x4000000).into();
        let dx = from_raw(sx - 0x2000000);
        let dy = from_raw(sy - 0x2000000);
        let a = point_to_angle(dx, dy);
        let b = point_to_angle(fixed::neg(dx), fixed::neg(dy));
        // The two must be a half turn apart, up to the off-by-one that Doom's
        // `ANG90 - 1` style constants introduce at octant boundaries.
        let d = angular_delta(add(a, ANG180), b);
        assert(!felt_ge(d, 3), 'opposite vectors');
        i += 1;
    }
}

#[test]
fn test_point_to_angle2_is_the_difference_of_two_points() {
    let a = point_to_angle2(from_units(10), from_units(10), from_units(20), from_units(30));
    let b = point_to_angle(from_units(10), from_units(20));
    assert(a == b, 'point_to_angle2');
}

#[test]
fn test_slope_div_edge_cases() {
    assert(slope_div(0, 0) == SLOPERANGE, 'zero denominator saturates');
    assert(slope_div(1, 511) == SLOPERANGE, 'below 512 saturates');
    assert(slope_div(0, 65536) == 0, 'zero numerator');
    assert(slope_div(65536, 65536) == SLOPERANGE, 'equal is a full slope');
    assert(slope_div(65536 * 4, 65536) == SLOPERANGE, 'clamped above 2048');
    assert(slope_div(32768, 65536) == 1024, 'half slope');
}
