#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Line-coverage report for `doom_map`'s **accessor code** (PLAN.md §3.1
rule 4, C7).

Two departures from `cairo/crates/*/bench/coverage.py`, both forced:

1. A `doom/*` crate's path dependencies reach out of its own directory into
   `cairo/crates/*`, so the copy keeps the whole `cairo/{crates,doom}`
   layout rather than just the crate's siblings.

2. **The real level data cannot be compiled under coverage.** `cairo-coverage`
   0.5.0 refuses to run unless the manifest sets `inlining-strategy =
   "avoid"`, and with that flag `universal-sierra-compiler` fails on this
   crate with `Offset overflow` -- 17 904 felts of `const` arrays push a jump
   offset past the i16 the CASM encoding allows. (Verified: the failure is
   the *data*, not the tests; it reproduces with a single one-line test.)
   So the copy swaps `src/levels/e1m1.cairo` for a **miniature level of the
   same shape** -- five linedefs chosen to reach all four sign combinations
   of `linedef_v1`, one BSP node, two subsectors, two sectors, a 2x2
   blockmap -- and `src/tests.cairo` for a module that calls every public
   accessor on it. What is measured is therefore exactly what the target
   says: the coverage of the accessor code in `src/lib.cairo`, on data whose
   *values* do not matter. The 25 committed tests in `src/tests.cairo` are
   what check the real E1M1 values, under `scarb test`.

The fixture's half-plane coefficients are computed by importing
`scripts/gen_level.py`, so the fixture and the shipped data are built by the
same code.

`cairo-coverage` 0.5.0 emits no `BRF`/`BRH` records, so **branch** coverage
cannot be reported by the tool. Line coverage is the proxy, and since
`scarb fmt` puts every branch arm on its own line, a missed arm shows up as
a missed line.

Usage: `python3 coverage.py` (needs `snforge` and `cairo-coverage` on PATH).
"""

from __future__ import annotations

import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

CRATE = pathlib.Path(__file__).resolve().parent.parent
CAIRO = CRATE.parent.parent
sys.path.insert(0, str(CRATE / "scripts"))
import gen_level as G  # noqa: E402

TOOL_VERSIONS = "scarb 2.16.0\nstarknet-foundry 0.57.0\ncairo-coverage 0.5.0\n"
PROFILE = """
[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"
"""

# Five segments, one per sign combination of (ldx, ldy) plus a degenerate
# one, so that both arms of every `if` in `linedef_v1`/`linedef_v2` run.
FIXTURE_LINES = [
    ((0, 0), (64, 0)),  # ldx > 0, ldy = 0   -> diag 0
    ((64, 0), (0, 0)),  # ldx < 0, ldy = 0   -> diag 1
    ((0, 0), (64, 64)),  # ldx > 0, ldy > 0  -> diag 0
    ((64, 64), (0, 0)),  # ldx < 0, ldy < 0  -> diag 0
    ((0, 64), (64, 0)),  # ldx > 0, ldy < 0  -> diag 1
]

SLIM_TESTS = """// SPDX-License-Identifier: GPL-2.0-only
//! GENERATED BY bench/coverage.py -- the accessor exercise, over the
//! miniature level that replaces E1M1 for the coverage run. The real tests
//! are the 25 in the committed `src/tests.cairo`.

use blockmap::{cell_index, cell_of, list_item, list_range};
use geom2d::Point;
use super::*;

fn probe(x: felt252, y: felt252) -> Point {
    Point { x: fixed::from_units(x), y: fixed::from_units(y) }
}

#[test]
fn test_every_accessor_runs() {
    let m = load(LevelId::E1M1);
    let g = genesis(LevelId::E1M1);
    assert(g.id == m.id, 'same level');
    assert(num_linedefs(@m) == 5, 'lines');
    assert(num_sectors(@m) == 2, 'sectors');
    assert(num_subsectors(@m) == 2, 'subsectors');
    assert(num_things(@m) == 2, 'things');
    assert(things(@m).len() == 2, 'things span');

    let mut i: u32 = 0;
    while i != 5 {
        let line = linedef(@m, i);
        assert(line.hp.ab == linedef_half_plane(@m, i).ab, 'half plane');
        assert(line.bbox.left == linedef_box(@m, i).left, 'box');
        assert(line.flags == linedef_flags(@m, i), 'flags');
        assert(line.diag == linedef_diagonal(@m, i), 'diag');
        let (special, tag) = linedef_special(@m, i);
        assert(line.special == special && line.tag == tag, 'special');
        let (front, back) = linedef_sectors(@m, i);
        assert(line.front_sector == front && line.back_sector == back, 'sectors');
        let v1 = linedef_v1(@m, i);
        let v2 = linedef_v2(@m, i);
        assert(v1 != v2 || i == 99, 'two ends');
        i += 1;
    }

    let s = sector(@m, 0);
    assert(s.floor == sector_floor(@m, 0), 'floor');
    assert(s.ceiling == sector_ceiling(@m, 0), 'ceiling');
    let _ = sector(@m, 1);

    let p = probe(16, 16);
    let q = probe(48, 48);
    let ss = subsector_at(@m, p);
    assert(subsector_sector(@m, ss) < 2, 'subsector sector');
    assert(node_side(@m, 0, p, geom2d::hoist(p)) < 2, 'node side');
    assert(node_side(@m, 0, q, geom2d::hoist(q)) < 2, 'node side 2');
    let _ = nodes(@m);

    let grid = grid(@m);
    let (cx, cy) = cell_of(grid, p).unwrap();
    let cell = cell_index(grid, cx, cy);
    assert(subsector_in_cell(@m, cell, p) == ss, 'accelerated');
    let (from, to) = subsector_candidates(@m, cell);
    let mut k = from;
    while k != to {
        assert(subsector_candidate(@m, k) < 2, 'candidate');
        k += 1;
    }
    assert(descent_start(@m, cell) == descent_start(@m, cell), 'pure');

    let lists = blockmap_lists(@m);
    let (lo, hi) = list_range(@lists, cell);
    let mut j = lo;
    while j != hi {
        assert(list_item(@lists, j) < 5, 'blockmap item');
        j += 1;
    }

    assert(reject(@m, 0, 1), 'blocked pair');
    assert(!reject(@m, 0, 0), 'self visible');
    assert(reject(@m, 1, 0), 'symmetric');

    let t0 = thing(@m, 0);
    let t1 = thing(@m, 1);
    assert(t0.doomednum == 1, 'player start');
    assert(t1.doomednum == 3004, 'zombieman');
    assert(t0.angle != t1.angle, 'different angles');
    assert(t0.position != t1.position, 'different places');

    // The transitional API, so the compat module is covered too.
    let level = sample_level();
    assert(sector_at(@level, 0).light_level == 200, 'compat sector');
    assert(is_line_blocking(@level, 0), 'compat line');
}
"""


def fixture_level() -> str:
    """A miniature level with the same array names and shapes as a real one."""
    arr = G.Arrays()
    ab, bb, cb, lr, bt, pk = [], [], [], [], [], []
    for v1, v2 in FIXTURE_LINES:
        a, b, c = G.half_plane(v1, v2)
        ab.append(a)
        bb.append(b)
        cb.append(c)
        lr.append(G.enc(min(v1[0], v2[0])) * G.BOX_SHIFT + G.enc(max(v1[0], v2[0])))
        bt.append(G.enc(min(v1[1], v2[1])) * G.BOX_SHIFT + G.enc(max(v1[1], v2[1])))
        pk.append(
            (1 << G.LP_FLAGS)
            | (11 << G.LP_SPECIAL)
            | (3 << G.LP_TAG)
            | (G.diagonal(v1, v2) << G.LP_DIAG)
            | (0 << G.LP_FRONT)
            | (1 << G.LP_BACK)
        )
    arr.add("L_AB", "felt252", ab, "linedefPredicates")
    arr.add("L_BB", "felt252", bb, "linedefPredicates")
    arr.add("L_CB", "felt252", cb, "linedefPredicates")
    arr.add("L_BOX_LR", "felt252", lr, "linedefBox")
    arr.add("L_BOX_BT", "felt252", bt, "linedefBox")
    arr.add("L_PACKED", "felt252", pk, "linedefMeta")

    # One node: the diagonal (0, 0) -> (64, 64), front leaf 0, back leaf 1.
    na, nb, nc = G.half_plane((0, 0), (64, 64))
    arr.add("N_AB", "felt252", [na], "nodePredicates")
    arr.add("N_BB", "felt252", [nb], "nodePredicates")
    arr.add("N_CB", "felt252", [nc], "nodePredicates")
    arr.add("N_CHILD0", "u32", [G.SUBSECTOR_FLAG + 0], "nodeChildren")
    arr.add("N_CHILD1", "u32", [G.SUBSECTOR_FLAG + 1], "nodeChildren")

    arr.add("SS_SECTOR", "u32", [0, 1], "subsectorSector")
    arr.add("S_FLOOR", "felt252", [G.enc(0), G.enc(8)], "sectorHeights")
    arr.add("S_CEIL", "felt252", [G.enc(128), G.enc(120)], "sectorHeights")
    arr.add(
        "S_META",
        "felt252",
        [(160 << G.SM_LIGHT) | (9 << G.SM_SPECIAL) | (3 << G.SM_TAG), 255],
        "sectorMeta",
    )

    # A 2 x 2 grid of 128-unit cells at the origin; every cell holds one line.
    arr.add("BM_START", "u32", [0, 1, 2, 3, 4], "blockmap")
    arr.add("BM_ITEMS", "u32", [0, 1, 2, 3], "blockmap")
    arr.add("ACCEL_START", "u32", [0, 2, 3, 4, 5], "accelerator")
    packed = []
    items = [0, 1, 0, 1, 0]
    for i in range(0, len(items), G.ACCEL_PER_FELT):
        word = 0
        for k, v in enumerate(items[i : i + G.ACCEL_PER_FELT]):
            word |= v << (G.ACCEL_BITS * k)
        packed.append(word)
    arr.add("ACCEL_PACKED", "felt252", packed, "accelerator")
    # Cell 0 straddles the partition (start at the root), the others do not.
    arr.add(
        "CELL_NODE",
        "u32",
        [0, G.SUBSECTOR_FLAG + 0, G.SUBSECTOR_FLAG + 1, 0],
        "accelerator",
    )
    # Two sectors, one felt per row: 0 cannot see 1 and vice versa.
    arr.add("REJECT_ROWS", "felt252", [0b10, 0b01], "reject")
    arr.add("POW2", "felt252", [1 << k for k in range(G.REJECT_BITS)], "reject")
    things = []
    for x, y, ty, angle, flags in ((16, 16, 1, 0, 7), (48, 48, 3004, 90, 7)):
        things.append(
            ((x + G.COORD_BIAS) << G.TH_X)
            | ((y + G.COORD_BIAS) << G.TH_Y)
            | (ty << G.TH_TYPE)
            | ((angle // 45) << G.TH_ANGLE)
            | (flags << G.TH_FLAGS)
        )
    arr.add("THINGS", "felt252", things, "things")

    meta = dict(
        map="E1M1",
        num_linedefs=5,
        num_nodes=1,
        root_node=0,
        num_subsectors=2,
        num_sectors=2,
        num_things=2,
        columns=2,
        rows=2,
        origin_x=0,
        origin_y=0,
        reject_stride=1,
        skill_bit=2,
        start=dict(x=16, y=16, angle=0),
        bbox=dict(minX=0, minY=0, maxX=64, maxY=64),
    )
    return G.emit_level(arr, meta)


def patch(root: pathlib.Path) -> None:
    (root / ".tool-versions").write_text(TOOL_VERSIONS)
    manifest = root / "Scarb.toml"
    text = manifest.read_text()
    text = text.replace("version.workspace = true", 'version = "0.1.0"')
    text = text.replace("edition.workspace = true", 'edition = "2024_07"')
    text = text.replace("cairo_test.workspace = true", 'snforge_std = "0.57.0"')
    if "[profile.dev.cairo]" not in text:
        text += PROFILE
    manifest.write_text(text)


def first_test_line(source: pathlib.Path) -> int:
    """Line from which a file is test code, or `maxsize` if it never is.

    A bare `#[cfg(test)] mod tests;` **declaration** is not a cutoff: the
    module's body is a separate file, already excluded by name, and the
    production code of this crate continues below it (unlike the generic
    crates, where the inline test module sits at the bottom).
    """
    if not source.exists():
        return sys.maxsize
    lines = source.read_text().splitlines()
    for number, line in enumerate(lines, start=1):
        if line.startswith("#[cfg(test)]"):
            following = lines[number] if number < len(lines) else ""
            if following.strip().endswith(";"):
                continue
            return number
    return sys.maxsize


# Generated data and the test module itself are not accessor code.
EXCLUDED = ("levels/", "tests.cairo")


def main() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        root = pathlib.Path(tmp) / "cairo"
        root.mkdir()
        ignore = shutil.ignore_patterns("target", "bench", "coverage", "__pycache__")
        shutil.copytree(CAIRO / "crates", root / "crates", ignore=ignore)
        shutil.copytree(CAIRO / "doom", root / "doom", ignore=ignore)
        for group in ("crates", "doom"):
            for package in (root / group).iterdir():
                if package.is_dir() and (package / "Scarb.toml").exists():
                    patch(package)
        work = root / "doom" / CRATE.name
        (work / "src" / "levels" / "e1m1.cairo").write_text(fixture_level())
        shutil.rmtree(work / "src" / "tests", ignore_errors=True)
        (work / "src" / "tests.cairo").write_text(SLIM_TESTS)

        proc = subprocess.run(
            ["snforge", "test", "--coverage"], cwd=work, capture_output=True, text=True
        )
        if proc.returncode != 0:
            print(proc.stdout[-4000:], proc.stderr[-2000:], sep="\n")
            return 1
        tests = re.search(r"Tests: (\d+) passed", proc.stdout)

        lcov = (work / "coverage" / "coverage.lcov").read_text()
        source: pathlib.Path | None = None
        cutoff = sys.maxsize
        skip = False
        hit = total = 0
        uncovered: list[str] = []
        for line in lcov.splitlines():
            if line.startswith("SF:"):
                source = pathlib.Path(line[3:])
                skip = any(marker in str(source) for marker in EXCLUDED)
                cutoff = first_test_line(source)
                continue
            if skip:
                continue
            match = re.match(r"^DA:(\d+),(\d+)$", line)
            if match and int(match.group(1)) < cutoff:
                total += 1
                if int(match.group(2)) > 0:
                    hit += 1
                elif source is not None:
                    uncovered.append("%s:%s" % (source.name, match.group(1)))

    percent = 100.0 * hit / total if total else 0.0
    print(
        "%s accessors: %s test(s), production lines %d/%d = %.1f%%"
        % (CRATE.name, tests.group(1) if tests else "?", hit, total, percent)
    )
    if uncovered:
        print("uncovered: " + ", ".join(uncovered))
    return 0 if percent >= 90.0 else 1


if __name__ == "__main__":
    sys.exit(main())
