#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Line-coverage report for `doom_game`'s glue (PLAN.md §3.1 rule 4, C7).

The method of `doom_player/bench/coverage.py`, whose helpers this imports:
`cairo-coverage` 0.5.0 only reads `snforge` traces, refuses to run without
`inlining-strategy = "avoid"`, and under that flag `doom_map`'s real E1M1
constants fail to compile (`Offset overflow`). So the copy of the
`cairo/{crates,doom}` tree gets `doom_map`'s miniature level with
`doom_specials`' tables regenerated from it, and this crate's test module
is reduced to `src/tests/synthetic.cairo` — the level-independent glue
tests (the record, the readers, the guards, the engine, the snapshot
layout, and every event applier on hand-built mobjs). The golden replays
of `src/tests/e1m1.cairo` run under `scarb test`, not here.

`doom_game` links the whole graph, so the suite is measured in as many
passes as compile (`bisect`, from doom_player's script): a line counts as
covered when any pass covered it.

Production lines only (`src/tests.cairo` and `src/tests/` excluded). The
script exits non-zero below 90 % (C7).

Usage: `python3 coverage.py` (needs `snforge` and `cairo-coverage` on PATH).
"""

from __future__ import annotations

import os
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

CRATE = pathlib.Path(__file__).resolve().parent.parent
CAIRO = CRATE.parent.parent
sys.path.insert(0, str(CAIRO / "doom" / "doom_map" / "bench"))
sys.path.insert(0, str(CAIRO / "doom" / "doom_specials" / "scripts"))
sys.path.insert(0, str(CAIRO / "doom" / "doom_player" / "bench"))
import coverage as map_coverage  # noqa: E402  (doom_map's: fixture_level, patch)
import gen_specials as S  # noqa: E402
from coverage import bisect, test_names  # noqa: E402  (doom_player's bisect over the suite)
import coverage as player_coverage  # noqa: E402

SLIM_TESTS = """// SPDX-License-Identifier: GPL-2.0-only
//! GENERATED BY bench/coverage.py -- only the level-agnostic glue module.
mod synthetic;
"""

EXCLUDED = ("tests.cairo", "/tests/")


def main() -> int:
    keep_dir = os.environ.get("COVERAGE_KEEP")
    with tempfile.TemporaryDirectory() as tmp:
        root = pathlib.Path(keep_dir if keep_dir else tmp) / "cairo"
        shutil.rmtree(root, ignore_errors=True)
        root.mkdir(parents=True)
        ignore = shutil.ignore_patterns("target", "bench", "coverage", "__pycache__")
        shutil.copytree(CAIRO / "crates", root / "crates", ignore=ignore)
        shutil.copytree(CAIRO / "doom", root / "doom", ignore=ignore)
        for group in ("crates", "doom"):
            for package in (root / group).iterdir():
                if package.is_dir() and (package / "Scarb.toml").exists():
                    map_coverage.patch(package)

        level = root / "doom" / "doom_map" / "src" / "levels" / "e1m1.cairo"
        level.write_text(map_coverage.fixture_level())
        text, _ = S.build(S.load_level(level))
        (root / "doom" / "doom_specials" / "src" / "level" / "e1m1.cairo").write_text(text)

        work = root / "doom" / CRATE.name
        (work / "src" / "tests.cairo").write_text(SLIM_TESTS)
        (work / "src" / "tests" / "e1m1.cairo").unlink()

        source = (work / player_coverage.SOURCE).read_text()
        names = test_names(source)
        print("%s: %d tests, measured in as few passes as compile" % (CRATE.name, len(names)))
        runs = bisect(work, source, names)

        hits: dict = {}
        tests = 0
        for lcov, passed in runs:
            tests += passed
            source_file = None
            skip = False
            for line in lcov.splitlines():
                if line.startswith("SF:"):
                    source_file = pathlib.Path(line[3:])
                    skip = str(work) not in str(source_file) or any(
                        m in str(source_file) for m in EXCLUDED
                    )
                    continue
                if skip:
                    continue
                match = re.match(r"^DA:(\d+),(\d+)$", line)
                if match and source_file is not None:
                    key = (source_file.name, int(match.group(1)))
                    hits[key] = max(hits.get(key, 0), int(match.group(2)))

    total = len(hits)
    hit = sum(1 for v in hits.values() if v > 0)
    per_file: dict = {}
    uncovered: list = []
    for (name, line), count in sorted(hits.items()):
        counts = per_file.setdefault(name, [0, 0])
        counts[1] += 1
        if count > 0:
            counts[0] += 1
        else:
            uncovered.append("%s:%d" % (name, line))
    percent = 100.0 * hit / total if total else 0.0
    print(
        "\n%s: %d test(s) over %d pass(es), production lines %d/%d = %.1f%%"
        % (CRATE.name, tests, len(runs), hit, total, percent)
    )
    for name, (h, t) in sorted(per_file.items()):
        print("  %-18s %4d/%4d" % (name, h, t))
    if uncovered:
        print("uncovered: " + ", ".join(uncovered))
    return 0 if percent >= 90.0 else 1


if __name__ == "__main__":
    sys.exit(main())
