# SPDX-License-Identifier: GPL-2.0-only
# The "with data" side of the bytecode measurement: the smallest executable
# that references every generated `const` table once. `../baseline` is the
# same package with the data left out; the difference between the two
# compiled sizes is what the tables cost (docs/G0.md D4, R2-A12).
[package]
name = "doom_things_size"
version = "0.1.0"
edition = "2024_07"

[dependencies]
doom_things = { path = "../.." }
cairo_execute = "2.16.0"

[[target.executable]]
name = "doom_things_size"
function = "doom_things_size::main"
sierra = true

[cairo]
enable-gas = false
