# SPDX-License-Identifier: GPL-2.0-only
# The "with the player" side of the bytecode measurement: the smallest
# executable that calls every public entry point of `doom_player` once on the
# loaded level. `../baseline` is the same package with the same level and
# table data but no `doom_player` call; the difference between the two
# compiled sizes is what this crate's code costs (docs/DECISIONS.md D23).
[package]
name = "doom_player_size"
version = "0.1.0"
edition = "2024_07"

[dependencies]
doom_player = { path = "../.." }
doom_physics = { path = "../../../doom_physics" }
doom_specials = { path = "../../../doom_specials" }
doom_map = { path = "../../../doom_map" }
doom_things = { path = "../../../doom_things" }
fixed = { path = "../../../../crates/fixed" }
geom2d = { path = "../../../../crates/geom2d" }
prng = { path = "../../../../crates/prng" }
ticcmd = { path = "../../../../crates/ticcmd" }
cairo_execute = "2.16.0"

[[target.executable]]
name = "doom_player_size"
function = "doom_player_size::main"
sierra = true

[cairo]
enable-gas = false
