[package]
name = "u32_loop"
version = "0.1.0"
edition = "2024_07"

[[target.executable]]
name = "u32_loop"
function = "u32_loop::main"

[dependencies]
cairo_execute = "2.19.4"

[cairo]
enable-gas = false
