#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate `src/tests/vectors.cairo` for the `fixed` crate.

Reference values are computed here with Python's arbitrary-precision
integers, using the exact semantics of Doom's `FixedMul` / `FixedDiv`:

    FixedMul(a, b) = (a * b) >> 16          # arithmetic shift == floor
    FixedDiv(a, b) = MAXINT / MININT        if (abs(a) >> 14) >= abs(b)
                   = trunc((a << 16) / b)   otherwise   (toward zero)

Values are emitted in this crate's offset encoding (`enc = raw + 2^32`) so
that every constant in the generated file is a non-negative felt, exactly
like the values the crate stores at run time.

Usage: python3 scripts/gen_vectors.py [> src/tests/vectors.cairo]
       python3 scripts/gen_vectors.py --write
"""

from __future__ import annotations

import sys
from pathlib import Path

BIAS = 1 << 32
RAW_MAX = (1 << 31) - 1
RAW_MIN = -(1 << 31)


def fixed_mul(a: int, b: int) -> int:
    return (a * b) >> 16  # Python's >> on negatives already floors


def fixed_div(a: int, b: int) -> int:
    if (abs(a) >> 14) >= abs(b):
        return RAW_MIN if (a < 0) != (b < 0) else RAW_MAX
    q = abs(a << 16) // abs(b)
    return -q if (a < 0) != (b < 0) else q


def lcg(state: int) -> int:
    return (state * 6364136223846793005 + 1442695040888963407) % (1 << 64)


def cases() -> list[tuple[int, int]]:
    """Deterministic (a_raw, b_raw) pairs: edge cases first, then a
    pseudo-random sweep over coordinate-sized and speed-sized values."""
    out: list[tuple[int, int]] = [
        (0, 0),
        (0, 65536),
        (65536, 0),
        (65536, 65536),
        (-65536, 65536),
        (65536, -65536),
        (-65536, -65536),
        (32768, 32768),
        (1, 1),
        (-1, 1),
        (1, -1),
        (-1, -1),
        (1, 65536),
        (-1, 65536),
        (RAW_MAX, 1),
        (RAW_MIN, 1),
        (RAW_MAX, 65536),
        (RAW_MIN, 65536),
        (RAW_MAX, RAW_MAX),
        (RAW_MIN, RAW_MIN),
        (RAW_MAX, RAW_MIN),
        # Doom's overflow guard: |a| >> 14 >= |b|
        (1 << 30, 1),
        (-(1 << 30), 1),
        (1 << 30, -1),
        (65536 * 100, 65536),
        (65536 * 100, -65536),
        # Typical Doom quantities: 24 units of momentum, 8192 units of range.
        (24 * 65536, 45000),
        (-24 * 65536, 45000),
        (8192 * 65536, 65536 // 2),
        (-8192 * 65536, -3),
    ]
    state = 0x1234567
    while len(out) < 160:
        state = lcg(state)
        a = (state % (1 << 27)) - (1 << 26)
        state = lcg(state)
        b = (state % (1 << 22)) - (1 << 21)
        if b == 0:
            b = 65536
        out.append((a, b))
    return out


HEADER = """// SPDX-License-Identifier: Apache-2.0
// GENERATED by scripts/gen_vectors.py -- do not edit by hand.
//
// Reference vectors for `fixed::mul` and `fixed::div`, computed with Python
// arbitrary-precision integers using Doom's FixedMul/FixedDiv semantics
// (see the generator for the exact formulas). All values are in this crate's
// offset encoding: `enc = raw + 2^32`.
"""


def emit(name: str, values: list[int]) -> str:
    body = ",\n    ".join(
        ", ".join(str(v) for v in values[i:i + 6]) for i in range(0, len(values), 6)
    )
    return "pub const %s: [felt252; %d] = [\n    %s,\n];\n" % (name, len(values), body)


def main() -> int:
    pairs = cases()
    # `mul` is only defined while the result stays in the documented domain
    # (|raw| < 2^32); pairs whose exact product leaves it (as Doom's own
    # int32 FixedMul would overflow) are kept for `div` only.
    mul_a, mul_b, mul_r = [], [], []
    div_a, div_b, div_r = [], [], []
    for a, b in pairs:
        assert -(1 << 32) < a < (1 << 32), a
        assert -(1 << 32) < b < (1 << 32), b
        m = fixed_mul(a, b)
        if -(1 << 32) < m < (1 << 32):
            mul_a.append(a + BIAS)
            mul_b.append(b + BIAS)
            mul_r.append(m + BIAS)
        d = fixed_div(a, b)
        assert -(1 << 32) < d < (1 << 32), (a, b, d)
        div_a.append(a + BIAS)
        div_b.append(b + BIAS)
        div_r.append(d + BIAS)

    text = HEADER + "\n"
    text += emit("MUL_A_ENC", mul_a) + "\n"
    text += emit("MUL_B_ENC", mul_b) + "\n"
    text += emit("MUL_R_ENC", mul_r) + "\n"
    text += emit("DIV_A_ENC", div_a) + "\n"
    text += emit("DIV_B_ENC", div_b) + "\n"
    text += emit("DIV_R_ENC", div_r)

    if "--write" in sys.argv:
        out = Path(__file__).resolve().parent.parent / "src" / "tests" / "vectors.cairo"
        out.write_text(text)
        print("wrote %s (%d mul, %d div cases)" % (out, len(mul_a), len(div_a)),
              file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
