// SPDX-License-Identifier: GPL-2.0-only
//! Compiled-in level data for the Hellproof core, and the typed accessors
//! that read it.
//!
//! The data itself is generated by `scripts/gen_level.py` out of the JSON
//! `tools/wad` extracts from `freedoom1.wad`, and lives in
//! [`levels::e1m1`] as plain `const` arrays. This module owns the
//! **representation contract**: which array holds what, how the packed
//! records are laid out, and how each one turns into the type a generic
//! crate consumes (`geom2d::HalfPlane`, `geom2d::Box`, `bsp::Nodes`,
//! `blockmap::Grid`/`PackedLists`, `fixed::Fixed`).
//!
//! # Layout policy
//!
//! S1 §5.9 measured that a `const` array element costs exactly one word of
//! compiled bytecode, and that the bootloader re-hashes the whole program on
//! every proof segment for `2 340 + 14.7 × words` steps. Program size is
//! therefore a per-tic cost amortized over K tics, and the arbitration rule
//! is
//!
//! ```text
//! pack iff  14.7 × (felts saved) / K  >  (extra steps per access) × (accesses per tic)
//! ```
//!
//! at K = 100. That puts the **hot** data planar (half-plane coefficients,
//! linedef boxes, node children, subsector→sector, blockmap lists, the
//! accelerator) and the **cold, bulky** data packed (linedef flags/special/
//! tag/sectors, sector metadata, THINGS, REJECT). `../README.md` records the
//! arithmetic per group and the measured cost of every accessor.
//!
//! Every packed felt stays **below 2^72** (S0's `range_check_9_9` cliff,
//! PLAN.md A7) — which is why REJECT is packed 64 bits per felt rather than
//! the 124 S1 §7 suggested.
//!
//! # What is not here
//!
//! SEGS, textures, flats, sidedef geometry and the BSP nodes' bounding boxes
//! are dropped: nothing in the simulation reads them (`bsp::point_in_subsector`
//! and `bsp::cross_bsp` never touch `Nodes::bbox`), and the renderer gets
//! them from the client JSON. Neither is the VERTEXES lump: a linedef's two
//! vertices are recovered exactly from its stored bounding box, its diagonal
//! bit and the sign of its deltas ([`linedef_v1`]/[`linedef_v2`]), which is
//! 3 567 words cheaper than storing VERTEXES plus a linedef→vertex mapping.

pub mod levels;

#[cfg(test)]
mod tests;
use bam::{ANG45, Angle};
use blockmap::{Grid, PackedLists};
use bsp::Nodes;
use fixed::Fixed;
use geom2d::{Box, HalfPlane, Point};
use levels::e1m1;

/// Sentinel in the 11-bit sector fields of `L_PACKED`: the linedef has no
/// sidedef on that side (Doom's `0xFFFF` sidedef index).
pub const NO_SECTOR: u32 = 2047;

/// Bits of REJECT packed into one felt (A7: the felt stays below 2^72).
pub const REJECT_BITS: u32 = 64;

// Shifts and widths of the packed records, as `u128` so that the decoders
// below are plain integer divisions (never `/` on a `felt252`, which is a
// field division — S1 §7, transverse rule 3).
const W16: u128 = 0x10000;
const W8: u128 = 0x100;
const W13: u128 = 0x2000;
const W11: u128 = 0x800;
const LP_SPECIAL: u128 = 0x10000; // 2^16
const LP_TAG: u128 = 0x1000000; // 2^24
const LP_DIAG: u128 = 0x10000000000; // 2^40
const LP_FRONT: u128 = 0x20000000000; // 2^41
const LP_BACK: u128 = 0x10000000000000; // 2^52
const SM_SPECIAL: u128 = 0x100; // 2^8
const SM_TAG: u128 = 0x10000; // 2^16
const TH_Y: u128 = 0x10000; // 2^16
const TH_TYPE: u128 = 0x100000000; // 2^32
const TH_ANGLE: u128 = 0x200000000000; // 2^45
const TH_FLAGS: u128 = 0x1000000000000; // 2^48
/// `fixed::BIAS - 2^15 * FRACUNIT`: turns a 16-bit biased map unit straight
/// into a `Fixed::enc` with one multiplication and one addition.
const COORD_OFFSET: felt252 = 0x80000000;

/// Doom's `ML_BLOCKING`.
pub const ML_BLOCKING: u32 = 1;
/// Doom's `ML_BLOCKMONSTERS`.
pub const ML_BLOCKMONSTERS: u32 = 2;
/// Doom's `ML_TWOSIDED`.
pub const ML_TWOSIDED: u32 = 4;

/// Which compiled-in level to load. One variant per generated module under
/// `src/levels/`; the felt id ([`LevelMap::id`]) is what `doom_game` puts in
/// the hashed state and `DoomRuns` records.
#[derive(Copy, Drop, Serde, PartialEq, Debug)]
pub enum LevelId {
    E1M1,
}

/// Every span of one compiled-in level, in the shapes the generic crates
/// consume. Built once by [`load`] and passed by snapshot.
#[derive(Copy, Drop)]
pub struct LevelMap {
    /// Short-string level id (`'E1M1'`).
    pub id: felt252,
    /// Linedef half-plane coefficients, `geom2d`'s biased planar form.
    pub l_ab: Span<felt252>,
    pub l_bb: Span<felt252>,
    pub l_cb: Span<felt252>,
    /// Linedef bounding box: four 16-bit biased map units in one felt
    /// (left, bottom, right, top from the low end), see [`unpack_box`].
    pub l_box: Span<felt252>,
    /// Linedef flags, special, tag, diagonal bit and the two face sectors.
    pub l_packed: Span<felt252>,
    /// BSP node partition predicates and children (`bsp::SUBSECTOR_FLAG`).
    pub n_ab: Span<felt252>,
    pub n_bb: Span<felt252>,
    pub n_cb: Span<felt252>,
    pub n_child0: Span<u32>,
    pub n_child1: Span<u32>,
    /// Root node id for a descent (`numnodes - 1`, as in Doom).
    pub root: u32,
    /// Subsector → sector, precomputed (S1 §7: never walk SEGS at run time).
    pub ss_sector: Span<u32>,
    /// Sector floor/ceiling heights, `Fixed::enc`.
    pub s_floor: Span<felt252>,
    pub s_ceil: Span<felt252>,
    /// Sector light level, special type and tag, packed.
    pub s_meta: Span<felt252>,
    /// The blockmap grid and its linedef lists.
    pub grid: Grid,
    pub blockmap: PackedLists,
    /// R2-A9 / D22: the deepest BSP child id whose region contains each cell.
    pub cell_node: Span<u32>,
    /// REJECT, `reject_stride` felts of 64 bits per sector row.
    pub reject: Span<felt252>,
    pub reject_stride: u32,
    /// Powers of two up to 2^63, for the REJECT bit extraction.
    pub pow2: Span<felt252>,
    /// THINGS kept at the configured skill, one packed felt each.
    pub things: Span<felt252>,
}

/// One linedef, fully decoded. Cold path (tests, `doom_specials`); the hot
/// paths read one field at a time with the accessors below.
#[derive(Copy, Drop, Serde, PartialEq, Debug)]
pub struct MapLine {
    pub hp: HalfPlane,
    pub bbox: Box,
    /// Raw WAD flags word (`ML_BLOCKING` &c.).
    pub flags: u32,
    /// `geom2d::diagonal`, the corner selector of `box_on_line_side`.
    pub diag: u8,
    pub special: u32,
    pub tag: u32,
    /// Sector behind the front sidedef, or [`NO_SECTOR`].
    pub front_sector: u32,
    /// Sector behind the back sidedef, or [`NO_SECTOR`].
    pub back_sector: u32,
}

/// One sector's simulation-relevant fields.
#[derive(Copy, Drop, Serde, PartialEq, Debug)]
pub struct MapSector {
    pub floor: Fixed,
    pub ceiling: Fixed,
    pub light: u32,
    pub special: u32,
    pub tag: u32,
}

/// One THINGS entry, as `P_SpawnMapThing` reads it.
#[derive(Copy, Drop, Serde, PartialEq, Debug)]
pub struct MapThing {
    pub position: Point,
    pub angle: Angle,
    /// The thing's `doomednum`, which `doom_things` maps to a `MobjType`.
    pub doomednum: u32,
    /// Raw WAD flags (skill bits, `MTF_AMBUSH`, `MTF_NOTSINGLE`).
    pub flags: u32,
}

/// Everything `doom_game::genesis` needs to build tic 0 of a run.
#[derive(Copy, Drop, Serde, PartialEq, Debug)]
pub struct Genesis {
    pub level: LevelId,
    /// Short-string level id, hashed into the genesis state.
    pub id: felt252,
    /// Player 1 start, in `fixed` encoding.
    pub start: Point,
    /// Player 1 start angle, BAM.
    pub angle: Angle,
    /// Number of THINGS to spawn from [`LevelMap::things`].
    pub num_things: u32,
}

/// D24, the **hot bundle**: the spans a per-tic consumer hoists once and
/// indexes directly inside its inner loops.
///
/// `LevelMap` has 24 fields and Cairo copies every one of them at each
/// `@LevelMap` call site (~51 steps, measured in `bench/`); an inner loop
/// over a blockmap cell's lines must not pay that per line. This bundle is
/// the subset the simulation reads every tic, with the cold data (`s_meta`,
/// `things`, `id`) left out. **Sector heights are deliberately absent**: a
/// door or a lift changes them, so `doom_physics` takes the *current*
/// floor/ceiling spans from the game state, not from the level constants.
///
/// It is still a struct of spans, so the same rule applies to it: pass it
/// once per top-level operation (`P_TryMove`, `P_CheckSight`) and hoist the
/// fields into locals before looping.
#[derive(Copy, Drop)]
pub struct HotMap {
    pub l_ab: Span<felt252>,
    pub l_bb: Span<felt252>,
    pub l_cb: Span<felt252>,
    pub l_box: Span<felt252>,
    pub l_packed: Span<felt252>,
    pub n_ab: Span<felt252>,
    pub n_bb: Span<felt252>,
    pub n_cb: Span<felt252>,
    pub n_child0: Span<u32>,
    pub n_child1: Span<u32>,
    pub root: u32,
    pub ss_sector: Span<u32>,
    pub cell_node: Span<u32>,
    pub grid: Grid,
    pub bm_start: Span<u32>,
    pub bm_items: Span<u32>,
    pub reject: Span<felt252>,
    pub reject_stride: u32,
    pub pow2: Span<felt252>,
}

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

/// Bundle the `const` arrays of `level` into spans.
///
/// Pure and total; the only allocation-free way to hand level data to the
/// generic crates. Call it once per segment and pass `@LevelMap` down.
pub fn load(level: LevelId) -> LevelMap {
    match level {
        LevelId::E1M1 => LevelMap {
            id: e1m1::LEVEL_ID,
            l_ab: e1m1::L_AB.span(),
            l_bb: e1m1::L_BB.span(),
            l_cb: e1m1::L_CB.span(),
            l_box: e1m1::L_BOX.span(),
            l_packed: e1m1::L_PACKED.span(),
            n_ab: e1m1::N_AB.span(),
            n_bb: e1m1::N_BB.span(),
            n_cb: e1m1::N_CB.span(),
            n_child0: e1m1::N_CHILD0.span(),
            n_child1: e1m1::N_CHILD1.span(),
            root: e1m1::ROOT_NODE,
            ss_sector: e1m1::SS_SECTOR.span(),
            s_floor: e1m1::S_FLOOR.span(),
            s_ceil: e1m1::S_CEIL.span(),
            s_meta: e1m1::S_META.span(),
            grid: Grid {
                origin_x: Fixed { enc: e1m1::BM_ORIGIN_X },
                origin_y: Fixed { enc: e1m1::BM_ORIGIN_Y },
                columns: e1m1::BM_COLUMNS,
                rows: e1m1::BM_ROWS,
            },
            blockmap: PackedLists { start: e1m1::BM_START.span(), items: e1m1::BM_ITEMS.span() },
            cell_node: e1m1::CELL_NODE.span(),
            reject: e1m1::REJECT_ROWS.span(),
            reject_stride: e1m1::REJECT_STRIDE,
            pow2: e1m1::POW2.span(),
            things: e1m1::THINGS.span(),
        },
    }
}

/// The D24 hot bundle of a loaded level (see [`HotMap`]).
pub fn hot(m: @LevelMap) -> HotMap {
    HotMap {
        l_ab: *m.l_ab,
        l_bb: *m.l_bb,
        l_cb: *m.l_cb,
        l_box: *m.l_box,
        l_packed: *m.l_packed,
        n_ab: *m.n_ab,
        n_bb: *m.n_bb,
        n_cb: *m.n_cb,
        n_child0: *m.n_child0,
        n_child1: *m.n_child1,
        root: *m.root,
        ss_sector: *m.ss_sector,
        cell_node: *m.cell_node,
        grid: *m.grid,
        bm_start: *m.blockmap.start,
        bm_items: *m.blockmap.items,
        reject: *m.reject,
        reject_stride: *m.reject_stride,
        pow2: *m.pow2,
    }
}

/// The genesis inputs of `level`.
pub fn genesis(level: LevelId) -> Genesis {
    match level {
        LevelId::E1M1 => Genesis {
            level,
            id: e1m1::LEVEL_ID,
            start: Point { x: Fixed { enc: e1m1::START_X }, y: Fixed { enc: e1m1::START_Y } },
            angle: e1m1::START_ANGLE,
            num_things: e1m1::NUM_THINGS,
        },
    }
}

// ---------------------------------------------------------------------------
// Packed-record decoders
// ---------------------------------------------------------------------------

/// `(packed / shift) % width`, the one bit-field extractor of this crate.
///
/// It is a plain `u128` division: `/` on a `felt252` is a *field* division
/// and is silently wrong (S1 §7, transverse rule 3).
fn field(packed: felt252, shift: u128, width: u128) -> u128 {
    let v: u128 = packed.try_into().unwrap();
    (v / shift) % width
}

/// A 16-bit biased map unit (`u + 2^15`) as a `Fixed`.
fn coord(biased: u128) -> Fixed {
    let b: felt252 = biased.into();
    Fixed { enc: b * 65536 + COORD_OFFSET }
}

/// Decode one `L_BOX` felt: `left | bottom << 16 | right << 32 | top << 48`,
/// each a 16-bit biased map unit.
///
/// Public so that `doom_physics` can decode a felt it has already read from
/// the hoisted span (D24) without paying the `@LevelMap` snapshot. Three
/// `u128` divmods: **measured ~40 steps** against ~90 for the previous
/// two-felt form.
pub fn unpack_box(packed: felt252) -> Box {
    let v: u128 = packed.try_into().unwrap();
    let w16: NonZero<u128> = 0x10000;
    let (q1, left) = DivRem::div_rem(v, w16);
    let (q2, bottom) = DivRem::div_rem(q1, w16);
    let (top, right) = DivRem::div_rem(q2, w16);
    Box { left: coord(left), bottom: coord(bottom), right: coord(right), top: coord(top) }
}

// ---------------------------------------------------------------------------
// Linedefs
// ---------------------------------------------------------------------------

/// Number of linedefs.
pub fn num_linedefs(m: @LevelMap) -> u32 {
    (*m.l_ab).len()
}

/// The stored half-plane predicate of linedef `i` — the hot accessor, three
/// `Span` reads and nothing else.
pub fn linedef_half_plane(m: @LevelMap, i: u32) -> HalfPlane {
    HalfPlane { ab: *(*m.l_ab).at(i), bb: *(*m.l_bb).at(i), cb: *(*m.l_cb).at(i) }
}

/// The bounding box of linedef `i`, the first half of `PIT_CheckLine`.
pub fn linedef_box(m: @LevelMap, i: u32) -> Box {
    unpack_box(*(*m.l_box).at(i))
}

/// Raw WAD flags word of linedef `i` (`ML_BLOCKING` &c.), the cheapest field
/// of the packed record: one read and one modulo.
pub fn linedef_flags(m: @LevelMap, i: u32) -> u32 {
    let v: u128 = (*(*m.l_packed).at(i)).try_into().unwrap();
    (v % W16).try_into().unwrap()
}

/// `geom2d::diagonal` of linedef `i`, the corner selector `box_on_line_side`
/// takes.
pub fn linedef_diagonal(m: @LevelMap, i: u32) -> u8 {
    field(*(*m.l_packed).at(i), LP_DIAG, 2).try_into().unwrap()
}

/// `(special, tag)` of linedef `i` — what `doom_specials` triggers on.
pub fn linedef_special(m: @LevelMap, i: u32) -> (u32, u32) {
    let packed = *(*m.l_packed).at(i);
    (
        field(packed, LP_SPECIAL, W8).try_into().unwrap(),
        field(packed, LP_TAG, W16).try_into().unwrap(),
    )
}

/// `(front_sector, back_sector)` of linedef `i`, [`NO_SECTOR`] when the side
/// has no sidedef. This is Doom's `sidedef → sector` resolved offline: the
/// SIDEDEFS lump is not compiled in.
pub fn linedef_sectors(m: @LevelMap, i: u32) -> (u32, u32) {
    let packed = *(*m.l_packed).at(i);
    (
        field(packed, LP_FRONT, W11).try_into().unwrap(),
        field(packed, LP_BACK, W11).try_into().unwrap(),
    )
}

/// The line's first vertex, recovered from its box and its deltas.
///
/// A segment's bounding box is the box of its two endpoints, so the endpoints
/// are two opposite corners of it; the signs of `ldx = ab - COEF_BIAS` and
/// `ldy = COEF_BIAS - bb` say which corner is `v1`. Exact for every line,
/// degenerate ones included (a horizontal line has `bottom == top`, so both
/// candidate corners coincide).
pub fn linedef_v1(m: @LevelMap, i: u32) -> Point {
    let b = linedef_box(m, i);
    let (neg_x, neg_y) = delta_signs(m, i);
    Point { x: if neg_x {
        b.right
    } else {
        b.left
    }, y: if neg_y {
        b.top
    } else {
        b.bottom
    } }
}

/// The line's second vertex, the opposite corner of [`linedef_v1`].
pub fn linedef_v2(m: @LevelMap, i: u32) -> Point {
    let b = linedef_box(m, i);
    let (neg_x, neg_y) = delta_signs(m, i);
    Point { x: if neg_x {
        b.left
    } else {
        b.right
    }, y: if neg_y {
        b.bottom
    } else {
        b.top
    } }
}

/// `(ldx < 0, ldy < 0)` of linedef `i`, read off its half-plane coefficients
/// (`A = ldx + COEF_BIAS`, `B = -ldy + COEF_BIAS`).
fn delta_signs(m: @LevelMap, i: u32) -> (bool, bool) {
    let ab = *(*m.l_ab).at(i);
    let bb = *(*m.l_bb).at(i);
    (!fixed::felt_ge(ab, geom2d::COEF_BIAS), fixed::felt_ge(bb, geom2d::COEF_BIAS + 1))
}

/// Linedef `i`, fully decoded. Cold path: four `Span` reads and five field
/// extractions. Hot callers use the single-field accessors above.
pub fn linedef(m: @LevelMap, i: u32) -> MapLine {
    let packed = *(*m.l_packed).at(i);
    let (front, back) = linedef_sectors(m, i);
    MapLine {
        hp: linedef_half_plane(m, i),
        bbox: linedef_box(m, i),
        flags: (field(packed, 1, W16)).try_into().unwrap(),
        diag: field(packed, LP_DIAG, 2).try_into().unwrap(),
        special: field(packed, LP_SPECIAL, W8).try_into().unwrap(),
        tag: field(packed, LP_TAG, W16).try_into().unwrap(),
        front_sector: front,
        back_sector: back,
    }
}

// ---------------------------------------------------------------------------
// Sectors and subsectors
// ---------------------------------------------------------------------------

/// Number of sectors.
pub fn num_sectors(m: @LevelMap) -> u32 {
    (*m.s_floor).len()
}

/// Floor height of sector `i` (`P_LineOpening`, gravity, damage floors).
pub fn sector_floor(m: @LevelMap, i: u32) -> Fixed {
    Fixed { enc: *(*m.s_floor).at(i) }
}

/// Ceiling height of sector `i`.
pub fn sector_ceiling(m: @LevelMap, i: u32) -> Fixed {
    Fixed { enc: *(*m.s_ceil).at(i) }
}

/// Sector `i`, fully decoded.
pub fn sector(m: @LevelMap, i: u32) -> MapSector {
    let meta = *(*m.s_meta).at(i);
    MapSector {
        floor: sector_floor(m, i),
        ceiling: sector_ceiling(m, i),
        light: field(meta, 1, W8).try_into().unwrap(),
        special: field(meta, SM_SPECIAL, W8).try_into().unwrap(),
        tag: field(meta, SM_TAG, W16).try_into().unwrap(),
    }
}

/// Number of BSP subsectors.
pub fn num_subsectors(m: @LevelMap) -> u32 {
    (*m.ss_sector).len()
}

/// The sector a subsector belongs to — precomputed, never walked through
/// SEGS → LINEDEF → SIDEDEF at run time (S1 §7: 44 steps saved per call).
pub fn subsector_sector(m: @LevelMap, subsector: u32) -> u32 {
    *(*m.ss_sector).at(subsector)
}

// ---------------------------------------------------------------------------
// BSP
// ---------------------------------------------------------------------------

/// The level's BSP as `bsp::Nodes`.
///
/// `bbox` is deliberately **empty**: neither `bsp::point_in_subsector` nor
/// `bsp::cross_bsp` reads it, and the 5 448 felts of node bounding boxes are
/// renderer-only data (the client reads them from the JSON). `bsp::child_box`
/// must therefore not be called on this bundle.
pub fn nodes(m: @LevelMap) -> Nodes {
    Nodes {
        ab: *m.n_ab,
        bb: *m.n_bb,
        cb: *m.n_cb,
        child0: *m.n_child0,
        child1: *m.n_child1,
        bbox: array![].span(),
    }
}

/// Which side of BSP node `node` the point `p` is on, `geom2d::SIDE_FRONT`
/// or `SIDE_BACK`, given `p`'s hoisted term (`geom2d::hoist`).
pub fn node_side(m: @LevelMap, node: u32, p: Point, rhs: felt252) -> u8 {
    geom2d::point_side_at(*m.n_ab, *m.n_bb, *m.n_cb, node, p, rhs)
}

/// The subsector containing `p`, by a full descent from the root
/// (`R_PointInSubsector`). The ground truth the accelerator is checked
/// against; prefer [`subsector_in_cell`] when the blockmap cell is known.
pub fn subsector_at(m: @LevelMap, p: Point) -> u32 {
    let nodes = nodes(m);
    bsp::point_in_subsector(@nodes, *m.root, p)
}

/// R2-A9 as decided in D22: the deepest BSP child id whose region contains
/// the whole of blockmap cell `cell`.
///
/// A partition is a linear function, so its extremes over an axis-aligned box
/// are attained at the box's corners; the generator walks down from the root
/// while all four corners of the cell agree, so descending from the returned
/// id answers **exactly** what a descent from the root answers, for every
/// point of that cell. One `Span` read, in every case — which is what S1 §7
/// demands of a location accelerator ("a partial accelerator is worse than
/// none": the uniform-cell shortcut cost 520 steps/tic more than it saved).
pub fn descent_start(m: @LevelMap, cell: u32) -> u32 {
    *(*m.cell_node).at(cell)
}

/// The subsector containing `p`, knowing that `p` lies in blockmap `cell`.
///
/// Equal to [`subsector_at`] for every `p` inside `cell` (asserted on a
/// lattice of sampled points by the crate's tests), for a descent of **4.15**
/// levels on average instead of 11.36 from the root on E1M1.
pub fn subsector_in_cell(m: @LevelMap, cell: u32, p: Point) -> u32 {
    let nodes = nodes(m);
    bsp::point_in_subsector(@nodes, descent_start(m, cell), p)
}

// ---------------------------------------------------------------------------
// Blockmap
// ---------------------------------------------------------------------------

/// The blockmap grid (origin, columns, rows) — `blockmap::cell_of` &c.
pub fn grid(m: @LevelMap) -> Grid {
    *m.grid
}

/// The blockmap's per-cell linedef lists, in `blockmap::PackedLists` form:
/// `blockmap::list_range` then `blockmap::list_item`, no array ever built
/// (R2-A10).
///
/// Named `blockmap_lists` rather than `blockmap` because a module-level item
/// called `blockmap` would shadow the crate of that name for the whole file.
pub fn blockmap_lists(m: @LevelMap) -> PackedLists {
    *m.blockmap
}

// ---------------------------------------------------------------------------
// REJECT
// ---------------------------------------------------------------------------

/// `true` when sector `s1` **cannot** see sector `s2` — Doom's REJECT bit,
/// which `P_CheckSight` consults before anything else (S1 §7 measured the
/// early-out at ×24.7).
///
/// The matrix is symmetric as vanilla node builders emit it; the crate's
/// tests assert it over all 33 124 pairs.
pub fn reject(m: @LevelMap, s1: u32, s2: u32) -> bool {
    reject_of(*m.reject, *m.reject_stride, *m.pow2, s1, s2)
}

/// [`reject`] on the hoisted spans (D24: `HotMap::reject`, `reject_stride`,
/// `pow2`), for `doom_physics`.
pub fn reject_of(
    reject: Span<felt252>, stride: u32, pow2: Span<felt252>, s1: u32, s2: u32,
) -> bool {
    let word: u128 = (*reject.at(s1 * stride + s2 / REJECT_BITS)).try_into().unwrap();
    let bit: u128 = (*pow2.at(s2 % REJECT_BITS)).try_into().unwrap();
    (word / bit) % 2 == 1
}

// ---------------------------------------------------------------------------
// Things
// ---------------------------------------------------------------------------

/// The packed THINGS of this level, at the skill the generator filtered for
/// (skill 2, "Hurt me plenty", docs/G0.md D3).
pub fn things(m: @LevelMap) -> Span<felt252> {
    *m.things
}

/// Number of things to spawn.
pub fn num_things(m: @LevelMap) -> u32 {
    (*m.things).len()
}

/// THINGS entry `i`, decoded.
pub fn thing(m: @LevelMap, i: u32) -> MapThing {
    let v: u128 = (*(*m.things).at(i)).try_into().unwrap();
    let angle_octant: felt252 = ((v / TH_ANGLE) % 8).into();
    MapThing {
        position: Point { x: coord(v % W16), y: coord((v / TH_Y) % W16) },
        angle: (angle_octant * ANG45.into()).try_into().unwrap(),
        doomednum: ((v / TH_TYPE) % W13).try_into().unwrap(),
        flags: ((v / TH_FLAGS) % W16).try_into().unwrap(),
    }
}
