# SPDX-License-Identifier: Apache-2.0
# Standalone package (NOT a member of the cairo/ workspace, like
# cairo/doom_contracts): it owns an executable target so that
# `scarb execute --print-resource-usage` can measure the step cost of the
# `bam` crate. See ../README.md ("Measured step costs").
[package]
name = "bam_bench"
version = "0.1.0"
edition = "2024_07"

[dependencies]
bam = { path = ".." }
fixed = { path = "../../fixed" }
cairo_execute = "2.16.0"

[[target.executable]]
name = "bam_bench"
function = "bam_bench::main"
sierra = true

[cairo]
enable-gas = false
