[package]
name = "doom_player"
version.workspace = true
edition.workspace = true

[dependencies]
bam = { path = "../../crates/bam" }
fixed = { path = "../../crates/fixed" }
fsm = { path = "../../crates/fsm" }
geom2d = { path = "../../crates/geom2d" }
prng = { path = "../../crates/prng" }
ticcmd = { path = "../../crates/ticcmd" }
doom_map = { path = "../doom_map" }
doom_things = { path = "../doom_things" }
doom_physics = { path = "../doom_physics" }
doom_specials = { path = "../doom_specials" }

[dev-dependencies]
cairo_test.workspace = true
