[package]
name = "doom_player"
version.workspace = true
edition.workspace = true

[dependencies]
fixed = { path = "../../crates/fixed" }
ticcmd = { path = "../../crates/ticcmd" }
doom_map = { path = "../doom_map" }
doom_things = { path = "../doom_things" }
doom_physics = { path = "../doom_physics" }
geom2d = { path = "../../crates/geom2d" }

[dev-dependencies]
cairo_test.workspace = true
