#!/usr/bin/env python3
"""Generate `src/lib.cairo` for `bigcode`: a program with a deliberately LARGE bytecode and a
short run (S4b measurement 2, D4).

Same shape as `spikes/s0/programs/bigcode/generate.py` (straight-line felt252 statements,
~4.0 bytecode words each), rebuilt here against Scarb 2.18 — the toolchain the recursion route's
packages use — so the leaf bootloader hashes exactly the bytecode we count. The `main` signature
returns a single felt252, which is what the leaf simple bootloader wraps into its 2 output cells.

Usage: generate.py [n_statements]   (default 4000 -> ~16 100 bytecode words)
"""

import os
import sys

N = int(sys.argv[1]) if len(sys.argv) > 1 else 4000
HERE = os.path.dirname(os.path.abspath(__file__))

lines = [
    "//! GENERATED by generate.py — do not edit.",
    "//!",
    "//! Large bytecode, tiny run: measures the program-length term of the leaf bootloader's",
    "//! overhead as a function of `program_hash_function` (S4b).",
    f"//! {N} straight-line felt252 statements.",
    "",
    "#[executable]",
    "fn main(n: u32) -> felt252 {",
    "    let mut a: felt252 = n.into();",
]
lines += [f"    a = a * {3 + (i % 7)} + {11 + i};" for i in range(N)]
lines += ["    a", "}", ""]

os.makedirs(os.path.join(HERE, "src"), exist_ok=True)
with open(os.path.join(HERE, "src", "lib.cairo"), "w") as fh:
    fh.write("\n".join(lines))
print(f"wrote {N} statements to src/lib.cairo")
