import { AssetIndex, MapData } from "./mapExtract.js";
import { linedefSpecialInfo } from "./lookup/linedefSpecials.js";
import { sectorSpecialName } from "./lookup/sectorSpecials.js";
import { thingTypeInfo } from "./lookup/thingTypes.js";
import { ThingFlag } from "./types.js";
import { rejectChunksPerRow } from "./recordPacking.js";

interface Count<T> {
  key: T;
  count: number;
}

function countBy<T>(items: T[], key: (item: T) => string): [string, number][] {
  const m = new Map<string, number>();
  for (const item of items) {
    const k = key(item);
    m.set(k, (m.get(k) ?? 0) + 1);
  }
  return [...m.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
}

function skillLabel(flags: number): string {
  const parts: string[] = [];
  if (flags & ThingFlag.EASY) parts.push("easy");
  if (flags & ThingFlag.MEDIUM) parts.push("medium");
  if (flags & ThingFlag.HARD) parts.push("hard");
  if (flags & ThingFlag.AMBUSH) parts.push("ambush");
  if (flags & ThingFlag.MULTIPLAYER_ONLY) parts.push("multiplayer-only");
  return parts.length ? parts.join("+") : "none";
}

export function buildReport(map: MapData, assets: AssetIndex): string {
  const lines: string[] = [];
  const push = (s = "") => lines.push(s);

  push(`# WAD extraction report: ${map.name} (freedoom1.wad)`);
  push();
  push(
    "> Generated by `tools/wad` (roadmap P0.2). This report drives the Phase 1 gameplay scope " +
      "decision (PLAN.md §7.4): which linedef specials, sector specials, and thing types the " +
      "Cairo core actually needs to implement for this map.",
  );
  push();

  push("## Counts");
  push();
  push("| Lump | Count |");
  push("|---|---:|");
  push(`| Vertexes | ${map.vertexes.length} |`);
  push(`| Linedefs | ${map.linedefs.length} |`);
  push(`| Sidedefs | ${map.sidedefs.length} |`);
  push(`| Sectors | ${map.sectors.length} |`);
  push(`| Subsectors | ${map.subsectors.length} |`);
  push(`| Segs | ${map.segs.length} |`);
  push(`| Nodes | ${map.nodes.length} |`);
  push(`| Things | ${map.things.length} |`);
  push();

  push("## Map bounding box");
  push();
  push(`- X: [${map.boundingBox.minX}, ${map.boundingBox.maxX}] (width ${map.boundingBox.maxX - map.boundingBox.minX} map units)`);
  push(`- Y: [${map.boundingBox.minY}, ${map.boundingBox.maxY}] (height ${map.boundingBox.maxY - map.boundingBox.minY} map units)`);
  push();

  push("## Blockmap");
  push();
  push(`- Grid: ${map.blockmap.columns} columns x ${map.blockmap.rows} rows (${map.blockmap.columns * map.blockmap.rows} cells)`);
  push(`- Origin: (${map.blockmap.originX}, ${map.blockmap.originY})`);
  const maxCellLines = Math.max(...map.blockmap.cells.map((c) => c.length));
  const avgCellLines = map.blockmap.cells.reduce((a, c) => a + c.length, 0) / map.blockmap.cells.length;
  push(`- Linedefs per cell: max ${maxCellLines}, average ${avgCellLines.toFixed(2)}`);
  push();

  push("## REJECT");
  push();
  const chunksPerRow = rejectChunksPerRow(map.reject.numSectors);
  push(`- Size: ${map.reject.data.length} bytes for ${map.reject.numSectors} sectors ` +
    `(${map.reject.numSectors}x${map.reject.numSectors} bit matrix, packed ${chunksPerRow} felt252 chunk(s)/row for Cairo)`);
  push();

  push("## Linedef special types");
  push();
  push("Distinct `specialType` values actually present on this map's linedefs, with counts and " +
    "vanilla Doom meaning:");
  push();
  push("| Special | Count | Category | Meaning |");
  push("|---:|---:|---|---|");
  const specialCounts = countBy(map.linedefs, (l) => String(l.specialType));
  for (const [key, count] of specialCounts) {
    const special = Number(key);
    const info = linedefSpecialInfo(special);
    push(`| ${special} | ${count} | ${info.category} | ${info.name} |`);
  }
  push();
  const nonZeroSpecials = map.linedefs.filter((l) => l.specialType !== 0).length;
  push(`(${nonZeroSpecials} of ${map.linedefs.length} linedefs carry a non-zero special.)`);
  push();

  push("## Sector special types");
  push();
  push("| Special | Count | Meaning |");
  push("|---:|---:|---|");
  const sectorSpecialCounts = countBy(map.sectors, (s) => String(s.specialType));
  for (const [key, count] of sectorSpecialCounts) {
    const special = Number(key);
    push(`| ${special} | ${count} | ${sectorSpecialName(special)} |`);
  }
  push();

  push("## Thing types");
  push();
  push("Counts are broken down by skill-flag combination (`easy`/`medium`/`hard`/`ambush`/" +
    "`multiplayer-only`) exactly as stored on each THINGS entry's `flags` field.");
  push();
  push("| Type | Category | Name | Total | By skill flags |");
  push("|---:|---|---|---:|---|");
  const byType = new Map<number, typeof map.things>();
  for (const t of map.things) {
    const arr = byType.get(t.type) ?? [];
    arr.push(t);
    byType.set(t.type, arr);
  }
  const sortedTypes = [...byType.entries()].sort((a, b) => b[1].length - a[1].length || a[0] - b[0]);
  for (const [type, occurrences] of sortedTypes) {
    const info = thingTypeInfo(type);
    const bySkill = countBy(occurrences, (t) => skillLabel(t.flags))
      .map(([label, count]) => `${label}: ${count}`)
      .join(", ");
    push(`| ${type} | ${info.category} | ${info.name} | ${occurrences.length} | ${bySkill} |`);
  }
  push();

  push("### Thing category summary");
  push();
  const categoryCounts = countBy(map.things, (t) => thingTypeInfo(t.type).category);
  push("| Category | Count |");
  push("|---|---:|");
  for (const [category, count] of categoryCounts) {
    push(`| ${category} | ${count} |`);
  }
  push();

  push("## Assets referenced by this map");
  push();
  push(`- Distinct wall textures referenced by sidedefs: ${assets.referencedTextures.length}`);
  push(`- Distinct flats referenced by sector floors/ceilings: ${assets.referencedFlats.length}`);
  push(`- PLAYPAL palettes: ${assets.playpalPaletteCount}, COLORMAP maps: ${assets.colormapMapCount}`);
  push(`- PNAMES patches: ${assets.pnamesCount}, TEXTURE1 textures: ${assets.texture1Count}` +
    (assets.texture2Count !== undefined ? `, TEXTURE2 textures: ${assets.texture2Count}` : ""));
  push(`- Flats in the WAD (F_START..F_END): ${assets.flats.length}`);
  push(`- Sprites in the WAD (S_START..S_END): ${assets.sprites.length}`);
  push();

  push("## Gameplay scope implied by this map");
  push();
  const monsterTypes = sortedTypes.filter(([t]) => thingTypeInfo(t).category === "monster");
  if (monsterTypes.length > 0) {
    push("Monsters that Phase 1 (`doom_monsters`) must implement for this map:");
    push();
    for (const [type, occurrences] of monsterTypes) {
      push(`- ${thingTypeInfo(type).name} (type ${type}): ${occurrences.length}`);
    }
  } else {
    push("No monster things found on this map.");
  }
  push();
  const specialCategories = new Set(
    map.linedefs.filter((l) => l.specialType !== 0).map((l) => linedefSpecialInfo(l.specialType).category),
  );
  push(
    `Linedef special categories present: ${specialCategories.size > 0 ? [...specialCategories].sort().join(", ") : "none"}.`,
  );
  push();

  return lines.join("\n") + "\n";
}
