#!/usr/bin/env python3
"""Generate src/lib.cairo for `bigcode`: a program with a deliberately LARGE
bytecode and a short run.

Purpose: separate the two halves of the privacy-bootloader step overhead — the
constant part, and the part proportional to the *program length*, because the
bootloader loads the task program into memory and hashes it. With ~300-word test
programs the two are indistinguishable; with 16 000 words they are not.

Usage: generate.py [n_statements]   (default 4000 -> ~16 100 bytecode words)
"""
import os
import sys

N = int(sys.argv[1]) if len(sys.argv) > 1 else 4000
HERE = os.path.dirname(os.path.abspath(__file__))

lines = [
    "//! GENERATED by generate.py — do not edit.",
    "//!",
    "//! A program with a deliberately large bytecode and a tiny run, used to measure",
    "//! the program-length term of the privacy-bootloader overhead (S0).",
    f"//! {N} straight-line felt252 statements.",
    "",
    "#[executable]",
    "fn main(n: u32) -> felt252 {",
    "    let mut a: felt252 = n.into();",
]
lines += [f"    a = a * {3 + (i % 7)} + {11 + i};" for i in range(N)]
lines += ["    a", "}", ""]

os.makedirs(os.path.join(HERE, "src"), exist_ok=True)
with open(os.path.join(HERE, "src", "lib.cairo"), "w") as fh:
    fh.write("\n".join(lines))
print(f"wrote {N} statements to src/lib.cairo")
