#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Line-coverage report for `doom_player` (PLAN.md §3.1 rule 4, C7).

Same method as `doom_physics`' and `doom_specials`' scripts, whose helpers
this one imports: `cairo-coverage` 0.5.0 only reads `snforge` traces,
refuses to run without `inlining-strategy = "avoid"`, and under that flag
`doom_map`'s real E1M1 constants fail to compile (`Offset overflow`). So the
copy of the `cairo/{crates,doom}` tree gets `doom_map`'s five-line fixture
level, with `doom_specials`' tables regenerated from it by the shipped
generator, and this crate's test module is reduced to
`src/tests/synthetic.cairo` -- the module that asserts no coordinate and
therefore runs on any level. The E1M1 reference vectors
(`src/tests/e1m1.cairo`) run under `scarb test`, not here.

**Why this one runs the suite in several passes.** `doom_player` links
`doom_map`, `doom_things`, `doom_physics` *and* `doom_specials`, and under
`inlining-strategy = "avoid"` the whole graph in one program walks into two
`universal-sierra-compiler` 2.19.3 limits:

* `Offset overflow`, when a function's frame grows past what an `i16` CASM
  offset can reach -- one call into `P_TouchSpecialThing` or `P_PlayerThink`
  costs thousands of cells with nothing inlined, so a handful in a row
  overflow. `src/tests/synthetic.cairo` is written in one-behaviour tests
  for exactly this reason;
* `assertion failed: Deferred(Const) does not match ZeroSized`, an internal
  panic that appears once the whole suite compiles and goes away when part
  of it is dead-code-eliminated.

Neither is anything the crate can fix, and both are a function of *how much*
is compiled at once. So this script splits the test list, measures each
part, and takes the union of the covered lines: a line counts as covered
when any pass covered it, which is what one pass over the whole suite would
have reported. `bisect` halves a group that fails to compile until every
group does.

Production lines only: `src/tests.cairo` and `src/tests/` are excluded.
`cairo-coverage` 0.5.0 emits no `BRF`/`BRH` records, so **branch** coverage
cannot be reported by the tool; line coverage is the proxy, and since
`scarb fmt` puts every branch arm on its own line, a missed arm shows up as a
missed line. The script exits non-zero below 90 % (C7).

Usage: `python3 coverage.py` (needs `snforge` and `cairo-coverage` on PATH).
"""

from __future__ import annotations

import os
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

CRATE = pathlib.Path(__file__).resolve().parent.parent
CAIRO = CRATE.parent.parent
sys.path.insert(0, str(CAIRO / "doom" / "doom_map" / "bench"))
sys.path.insert(0, str(CAIRO / "doom" / "doom_specials" / "scripts"))
import coverage as map_coverage  # noqa: E402  (doom_map's: fixture_level, patch)
import gen_specials as S  # noqa: E402

SLIM_TESTS = """// SPDX-License-Identifier: GPL-2.0-only
//! GENERATED BY bench/coverage.py -- only the level-agnostic rules module.
mod synthetic;
"""

EXCLUDED = ("tests.cairo", "/tests/")
SOURCE = "src/tests/synthetic.cairo"


def test_names(source: str) -> list[str]:
    return re.findall(r"^fn (test_\w+)\(", source, re.M)


def keep_only(source: str, keep: set[str]) -> str:
    """The module with every `#[test]` not in `keep` removed."""
    out: list[str] = []
    skip = False
    for line in source.splitlines(True):
        m = re.match(r"fn (test_\w+)\(", line)
        if m and m.group(1) not in keep:
            out.pop()  # the `#[test]` attribute above it
            skip = True
        if skip:
            if line == "}\n":
                skip = False
            continue
        out.append(line)
    return "".join(out)


def attempt(work: pathlib.Path, source: str, keep: list[str]):
    """Run `snforge test --coverage` over `keep`, or return `None` when the
    program will not compile for one of the two `universal-sierra-compiler`
    limits above."""
    (work / SOURCE).write_text(keep_only(source, set(keep)))
    shutil.rmtree(work / "coverage", ignore_errors=True)
    proc = subprocess.run(
        ["snforge", "test", "--coverage", "--max-n-steps", "500000000"],
        cwd=work,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        tail = proc.stdout[-2000:] + proc.stderr[-2000:]
        if "Offset overflow" in tail or "Deferred(Const)" in tail:
            return None
        print(proc.stdout[-4000:], proc.stderr[-2000:], sep="\n")
        raise SystemExit("snforge failed for a reason that is not a USC limit")
    passed = re.search(r"Tests: (\d+) passed", proc.stdout)
    lcov = (work / "coverage" / "coverage.lcov").read_text()
    return lcov, int(passed.group(1)) if passed else 0


def bisect(work: pathlib.Path, source: str, keep: list[str]) -> list:
    """Measure `keep` in as few passes as compile."""
    got = attempt(work, source, keep)
    if got is not None:
        print("  pass of %3d test(s): %d passed" % (len(keep), got[1]))
        return [got]
    if len(keep) == 1:
        # One test alone that will not compile: it is the only one whose
        # call graph reaches `doom_specials::use_line` (`player_tic`), and
        # that arm of `src/tic.cairo` therefore shows up as uncovered here.
        # `scarb test` runs it on the real level.
        print("  SKIPPED (does not compile alone): %s" % keep[0])
        return []
    half = len(keep) // 2
    return bisect(work, source, keep[:half]) + bisect(work, source, keep[half:])


def main() -> int:
    keep_dir = os.environ.get("COVERAGE_KEEP")
    with tempfile.TemporaryDirectory() as tmp:
        root = pathlib.Path(keep_dir if keep_dir else tmp) / "cairo"
        shutil.rmtree(root, ignore_errors=True)
        root.mkdir(parents=True)
        ignore = shutil.ignore_patterns("target", "bench", "coverage", "__pycache__")
        shutil.copytree(CAIRO / "crates", root / "crates", ignore=ignore)
        shutil.copytree(CAIRO / "doom", root / "doom", ignore=ignore)
        for group in ("crates", "doom"):
            for package in (root / group).iterdir():
                if package.is_dir() and (package / "Scarb.toml").exists():
                    map_coverage.patch(package)

        level = root / "doom" / "doom_map" / "src" / "levels" / "e1m1.cairo"
        level.write_text(map_coverage.fixture_level())
        text, _ = S.build(S.load_level(level))
        (root / "doom" / "doom_specials" / "src" / "level" / "e1m1.cairo").write_text(text)

        work = root / "doom" / CRATE.name
        (work / "src" / "tests.cairo").write_text(SLIM_TESTS)
        for extra in ("e1m1.cairo", "vectors.cairo"):
            (work / "src" / "tests" / extra).unlink()

        source = (work / SOURCE).read_text()
        names = test_names(source)
        print("%s: %d tests, measured in as few passes as compile" % (CRATE.name, len(names)))
        runs = bisect(work, source, names)

        # A line is covered when any pass covered it.
        hits: dict = {}
        tests = 0
        for lcov, passed in runs:
            tests += passed
            source_file = None
            skip = False
            for line in lcov.splitlines():
                if line.startswith("SF:"):
                    source_file = pathlib.Path(line[3:])
                    skip = str(work) not in str(source_file) or any(
                        m in str(source_file) for m in EXCLUDED
                    )
                    continue
                if skip:
                    continue
                match = re.match(r"^DA:(\d+),(\d+)$", line)
                if match and source_file is not None:
                    key = (source_file.name, int(match.group(1)))
                    hits[key] = max(hits.get(key, 0), int(match.group(2)))

    total = len(hits)
    hit = sum(1 for v in hits.values() if v > 0)
    per_file: dict = {}
    uncovered: list = []
    for (name, line), count in sorted(hits.items()):
        counts = per_file.setdefault(name, [0, 0])
        counts[1] += 1
        if count > 0:
            counts[0] += 1
        else:
            uncovered.append("%s:%d" % (name, line))

    percent = 100.0 * hit / total if total else 0.0
    print(
        "\n%s: %d test(s) over %d pass(es), production lines %d/%d = %.1f%%"
        % (CRATE.name, tests, len(runs), hit, total, percent)
    )
    for name, (h, t) in sorted(per_file.items()):
        print("  %-18s %4d/%4d" % (name, h, t))
    if uncovered:
        print("uncovered: " + ", ".join(uncovered))
    return 0 if percent >= 90.0 else 1


if __name__ == "__main__":
    sys.exit(main())
