#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Reference model for `doom_monsters`, over `tools/wad`'s JSON of a map.

A transcription of linuxdoom-1.10's `p_enemy.c` -- `P_Move`, `P_TryWalk`,
`P_NewChaseDir`, `P_CheckMeleeRange`, `P_CheckMissileRange`,
`P_LookForPlayers`, `A_Look` and `A_Chase` -- and **not** of the Cairo code.
It borrows two things it must not re-derive:

* the geometry, from `doom_physics/scripts/model.py`: `try_move`
  (`P_CheckPosition` in exact integers over the real E1M1) and
  `check_sight_exact` (`P_CheckSight` in exact rationals). Those two models
  are themselves checked bit-exactly against the Cairo physics by that
  crate's own vectors, so a disagreement here is this crate's;
* the `info.c` numbers, read out of `doom_things/src/tables.cairo` -- data,
  generated from the C tables by that crate and verified against `info.c` by
  its tests.

Everything else (the direction tables, the probability rules, the RNG order,
the state walk) is written here from the C semantics.

`--write` emits `src/tests/vectors.cairo`; the Cairo tests replay every
vector. Coordinates are emitted in `fixed`'s offset encoding
(`enc = raw + 2^32`) so that every felt stays non-negative and below 2^72.

Usage:
    python3 model.py --json <e1m1.json> [--write] [--seed 1]
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import random
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CRATE = HERE.parent
PHYSICS = CRATE.parent / "doom_physics" / "scripts"
THINGS = CRATE.parent / "doom_things" / "src" / "tables.cairo"

# Loaded under its own name: both files are called `model.py`, and a bare
# `import model` would find this one again.
_spec = importlib.util.spec_from_file_location("doom_physics_model", PHYSICS / "model.py")
phys = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(phys)

FRACUNIT = phys.FRACUNIT
BIAS = phys.BIAS
MAXSTEP = phys.MAXSTEP
NO_MOBJ = 0xFFFF

# -- p_enemy.c's own tables -------------------------------------------------

DI_EAST, DI_NORTHEAST, DI_NORTH, DI_NORTHWEST = 0, 1, 2, 3
DI_WEST, DI_SOUTHWEST, DI_SOUTH, DI_SOUTHEAST = 4, 5, 6, 7
DI_NODIR = 8
OPPOSITE = [DI_WEST, DI_SOUTHWEST, DI_SOUTH, DI_SOUTHEAST, DI_EAST, DI_NORTHEAST, DI_NORTH,
            DI_NORTHWEST, DI_NODIR]
DIAGS = [DI_NORTHWEST, DI_NORTHEAST, DI_SOUTHWEST, DI_SOUTHEAST]
XSPEED = [FRACUNIT, 47000, 0, -47000, -FRACUNIT, -47000, 0, 47000]
YSPEED = [0, 47000, FRACUNIT, 47000, 0, -47000, -FRACUNIT, -47000]

MELEERANGE = 64 * FRACUNIT
MISSILERANGE = 32 * 64 * FRACUNIT
SIGHT_TTL = 8
LOOK_CADENCE = 4
WINDOW = 8

MF_SOLID = 2
MF_SHOOTABLE = 4
MF_AMBUSH = 32
MF_JUSTATTACKED = 128
MF_JUSTHIT = 64
MF_COUNTKILL = 1 << 22

ANG90 = 0x40000000
ANG180 = 0x80000000
ANG270 = 0xC0000000
ANG45 = 0x20000000


def enc(raw: int) -> int:
    return raw + BIAS


# --------------------------------------------------------------------------
# `info.c` numbers, as generated by `doom_things`
# --------------------------------------------------------------------------


def parse_tables(path: Path) -> dict:
    txt = path.read_text()
    out: dict = {}
    for m in re.finditer(r"pub const ([A-Z0-9_]+): \[[a-z0-9]+; (\d+)\] = \[(.*?)\];", txt, re.S):
        name, n, body = m.group(1), int(m.group(2)), m.group(3)
        vals = [int(v) for v in body.replace("\n", " ").split(",") if v.strip()]
        if len(vals) != n:
            raise SystemExit("table %s: %d values for a length of %d" % (name, len(vals), n))
        out[name] = vals
    for m in re.finditer(r"pub const ([A-Z0-9_]+): u32 = (\d+);", txt):
        out[m.group(1)] = int(m.group(2))
    return out


T = parse_tables(THINGS)
FOREVER = 0xFFFFFFFF
NO_ACTION = 0
A_LOOK = T["A_LOOK"]
A_CHASE = T["A_CHASE"]
A_FACETARGET = T["A_FACETARGET"]
KINDS = {
    "possessed": T["KIND_POSSESSED"],
    "shotguy": T["KIND_SHOTGUY"],
    "troop": T["KIND_TROOP"],
    "sergeant": T["KIND_SERGEANT"],
    "shadows": T["KIND_SHADOWS"],
}


def mi(col: str, kind: int) -> int:
    return T["MI_" + col.upper()][kind]


def radius_of(kind: int) -> int:
    return T["MI_RADIUS"][kind] - BIAS


def height_of(kind: int) -> int:
    return T["MI_HEIGHT"][kind] - BIAS


class Rng:
    """`prng::Prng` over `doom_things`' `rndtable`: read, then advance."""

    def __init__(self, index: int) -> None:
        self.index = index % 256

    def next(self) -> int:
        v = T["RNDTABLE"][self.index]
        self.index = 0 if self.index == 255 else self.index + 1
        return v

    def sub_random(self) -> int:
        return self.next() - self.next()


# --------------------------------------------------------------------------
# A mobj, as much of one as the AI reads
# --------------------------------------------------------------------------


class Mon:
    def __init__(self, lv, kind: int, x: int, y: int, flags_extra: int = 0) -> None:
        self.kind = kind
        self.x, self.y = x, y
        self.radius = radius_of(kind)
        self.height = height_of(kind)
        self.sector = lv.sector_at(x, y)
        self.floorz, self.ceilingz = lv.sectors[self.sector]
        self.z = self.floorz
        self.angle = 0
        self.flags = mi("flags", kind) | flags_extra
        self.health = mi("spawnhealth", kind)
        self.state = mi("spawnstate", kind)
        self.tics = T["STATE_TICS"][self.state]
        self.target = NO_MOBJ
        self.reaction_time = mi("reactiontime", kind)
        self.threshold = 0
        self.move_dir = 0
        self.move_count = 0
        self.sight_expires = 0
        self.sight_sector = 0
        self.sight_ok = False

    def as_sight(self):
        return (self.x, self.y, self.z, self.height)


def check_sight(lv, a: Mon, b: Mon) -> bool:
    if lv.reject(a.sector, b.sector):
        return False
    visible, _ = phys.check_sight_exact(lv, a.as_sight(), b.as_sight())
    return visible


def check_sight_cached(lv, a: Mon, b: Mon, tic: int) -> bool:
    if tic < a.sight_expires and b.sector == a.sight_sector:
        return a.sight_ok
    ok = check_sight(lv, a, b)
    a.sight_ok = ok
    a.sight_sector = b.sector
    a.sight_expires = tic + SIGHT_TTL
    return ok


def approx_distance(dx: int, dy: int) -> int:
    """`P_AproxDistance`: `dx + dy - (min >> 1)` on absolute values."""
    dx, dy = abs(dx), abs(dy)
    return dx + dy - ((dy if dy < dx else dx) >> 1)


def blocked_by_thing(mo: Mon, x: int, y: int, others: list[Mon]) -> bool:
    """`PIT_CheckThing`'s solid half, for a walker."""
    for th in others:
        if th is mo:
            continue
        if not th.flags & (MF_SOLID | MF_SHOOTABLE):
            continue
        blockdist = th.radius + mo.radius
        if abs(th.x - x) >= blockdist or abs(th.y - y) >= blockdist:
            continue
        if th.flags & MF_SOLID:
            return True
    return False


def try_move(lv, mo: Mon, x: int, y: int, others: list[Mon]) -> bool:
    """`P_TryMove` for a walker: the physics model plus `PIT_CheckThing`."""
    if blocked_by_thing(mo, x, y, others):
        return False
    pm = phys.Mobj(mo.x, mo.y, mo.z, mo.radius, mo.height, False)
    ok, floorz, ceilingz, _dropoffz, _blocker, _crossed = phys.try_move(lv, pm, x, y)
    if not ok:
        return False
    mo.x, mo.y = x, y
    mo.floorz, mo.ceilingz = floorz, ceilingz
    mo.sector = lv.sector_at(x, y)
    return True


# --------------------------------------------------------------------------
# P_Move / P_TryWalk / P_NewChaseDir
# --------------------------------------------------------------------------


def p_move(lv, mo: Mon, others: list[Mon]) -> bool:
    if mo.move_dir >= DI_NODIR:
        return False
    speed = mi("speed", mo.kind)
    tryx = mo.x + speed * XSPEED[mo.move_dir]
    tryy = mo.y + speed * YSPEED[mo.move_dir]
    if not try_move(lv, mo, tryx, tryy, others):
        return False
    mo.z = mo.floorz
    return True


def try_walk(lv, mo: Mon, rng: Rng, others: list[Mon]) -> bool:
    if not p_move(lv, mo, others):
        return False
    mo.move_count = rng.next() & 15
    return True


def new_chase_dir(lv, mo: Mon, target: Mon, rng: Rng, others: list[Mon]) -> None:
    olddir = mo.move_dir
    turnaround = OPPOSITE[olddir]
    deltax = target.x - mo.x
    deltay = target.y - mo.y
    if deltax > 10 * FRACUNIT:
        d1 = DI_EAST
    elif deltax < -10 * FRACUNIT:
        d1 = DI_WEST
    else:
        d1 = DI_NODIR
    if deltay < -10 * FRACUNIT:
        d2 = DI_SOUTH
    elif deltay > 10 * FRACUNIT:
        d2 = DI_NORTH
    else:
        d2 = DI_NODIR
    if d1 != DI_NODIR and d2 != DI_NODIR:
        mo.move_dir = DIAGS[((1 if deltay < 0 else 0) << 1) + (1 if deltax > 0 else 0)]
        if mo.move_dir != turnaround and try_walk(lv, mo, rng, others):
            return
    if rng.next() > 200 or abs(deltay) > abs(deltax):
        d1, d2 = d2, d1
    if d1 == turnaround:
        d1 = DI_NODIR
    if d2 == turnaround:
        d2 = DI_NODIR
    if d1 != DI_NODIR:
        mo.move_dir = d1
        if try_walk(lv, mo, rng, others):
            return
    if d2 != DI_NODIR:
        mo.move_dir = d2
        if try_walk(lv, mo, rng, others):
            return
    if olddir != DI_NODIR:
        mo.move_dir = olddir
        if try_walk(lv, mo, rng, others):
            return
    order = range(DI_EAST, DI_SOUTHEAST + 1) if rng.next() & 1 else range(DI_SOUTHEAST, DI_EAST - 1, -1)
    for tdir in order:
        if tdir == turnaround:
            continue
        mo.move_dir = tdir
        if try_walk(lv, mo, rng, others):
            return
    if turnaround != DI_NODIR:
        mo.move_dir = turnaround
        if try_walk(lv, mo, rng, others):
            return
    mo.move_dir = DI_NODIR


# --------------------------------------------------------------------------
# Range checks
# --------------------------------------------------------------------------


def check_melee_range(lv, mo: Mon, target: Mon, tic: int) -> bool:
    dist = approx_distance(target.x - mo.x, target.y - mo.y)
    if dist >= MELEERANGE - 20 * FRACUNIT + target.radius:
        return False
    return check_sight_cached(lv, mo, target, tic)


def check_missile_range(lv, mo: Mon, target: Mon, rng: Rng, tic: int) -> bool:
    if not check_sight_cached(lv, mo, target, tic):
        return False
    if mo.flags & MF_JUSTHIT:
        mo.flags &= ~MF_JUSTHIT
        return True
    if mo.reaction_time:
        return False
    dist = approx_distance(mo.x - target.x, mo.y - target.y) - 64 * FRACUNIT
    if not mi("meleestate", mo.kind):
        dist -= 128 * FRACUNIT
    dist >>= 16  # arithmetic: floors toward minus infinity, as C does
    if dist > 200:
        dist = 200
    return not rng.next() < dist


# --------------------------------------------------------------------------
# A_Look / A_Chase
# --------------------------------------------------------------------------


def look_for_players(lv, mo: Mon, players: list[Mon], all_around: bool, tic: int) -> bool:
    for idx, p in enumerate(players):
        if p.health <= 0:
            continue
        if not check_sight_cached(lv, mo, p, tic):
            continue
        if not all_around:
            an = (phys_point_to_angle(mo.x, mo.y, p.x, p.y) - mo.angle) & 0xFFFFFFFF
            if ANG90 < an < ANG270:
                if approx_distance(p.x - mo.x, p.y - mo.y) > MELEERANGE:
                    continue
        mo.target = idx
        return True
    return False


def phys_point_to_angle(x1: int, y1: int, x2: int, y2: int) -> int:
    """`R_PointToAngle2` to BAM, through `bam`'s `tantoangle` construction.

    `bam::point_to_angle` is exercised bit-exactly by its own crate; the only
    thing this model needs from it is the octant, so the exact float
    `atan2` is enough here -- the vectors this feeds are generated with a
    margin (see `gen_looks`)."""
    import math

    a = math.atan2(y2 - y1, x2 - x1) / (2 * math.pi)
    return int((a % 1.0) * (1 << 32)) & 0xFFFFFFFF


def a_look(lv, mo: Mon, players: list[Mon], noise, rng: Rng, tic: int) -> bool:
    """Returns whether the monster woke up (and entered `seestate`)."""
    mo.threshold = 0
    seeyou = False
    if noise is not None:
        src_idx, src = noise
        if not lv.reject(mo.sector, src.sector) and src.flags & MF_SHOOTABLE:
            mo.target = src_idx
            if mo.flags & MF_AMBUSH:
                seeyou = check_sight_cached(lv, mo, src, tic)
            else:
                seeyou = True
    if not seeyou and not look_for_players(lv, mo, players, False, tic):
        return False
    # the see sound, and its `P_Random` when it picks inside a family
    see = SEESOUND[mo.kind] if mo.kind < len(SEESOUND) else 0
    if see:
        if 1 <= see <= 3 or 4 <= see <= 5:
            rng.next()
    enter_state(mo, mi("seestate", mo.kind))
    return True


SEESOUND = [0, 1, 2, 4, 6, 6, 0]
ACTIVESOUND = [0, 16, 16, 17, 18, 18, 0]


def enter_state(mo: Mon, state: int) -> int:
    mo.state = state
    mo.tics = T["STATE_TICS"][state]
    return T["STATE_ACTION"][state]


def a_chase(lv, mo: Mon, mobjs: list[Mon], rng: Rng, tic: int) -> int:
    if mo.reaction_time:
        mo.reaction_time -= 1
    target = mobjs[mo.target] if mo.target != NO_MOBJ and mo.target < len(mobjs) else None
    if mo.threshold:
        if target is None or target.health <= 0:
            mo.threshold = 0
        else:
            mo.threshold -= 1
    if mo.move_dir < DI_NODIR:
        octant = mo.angle // ANG45
        ang = octant * ANG45
        delta = (octant + DI_NODIR - mo.move_dir) % DI_NODIR
        if delta:
            ang = (ang - ANG45) & 0xFFFFFFFF if delta < 4 else (ang + ANG45) & 0xFFFFFFFF
        mo.angle = ang
    if target is None or not target.flags & MF_SHOOTABLE:
        if look_for_players(lv, mo, mobjs, True, tic):
            return NO_ACTION
        return enter_state(mo, mi("spawnstate", mo.kind))
    if mo.flags & MF_JUSTATTACKED:
        mo.flags &= ~MF_JUSTATTACKED
        new_chase_dir(lv, mo, target, rng, mobjs)
        return NO_ACTION
    melee = mi("meleestate", mo.kind)
    if melee and check_melee_range(lv, mo, target, tic):
        return enter_state(mo, melee)
    missile = mi("missilestate", mo.kind)
    if missile and mo.move_count == 0 and check_missile_range(lv, mo, target, rng, tic):
        mo.flags |= MF_JUSTATTACKED
        return enter_state(mo, missile)
    if mo.move_count == 0:
        new_chase_dir(lv, mo, target, rng, mobjs)
    else:
        mo.move_count -= 1
        if not p_move(lv, mo, mobjs):
            new_chase_dir(lv, mo, target, rng, mobjs)
    if ACTIVESOUND[mo.kind] if mo.kind < len(ACTIVESOUND) else 0:
        rng.next()
    return NO_ACTION


# --------------------------------------------------------------------------
# Vector generators
# --------------------------------------------------------------------------


def gen_chasedirs(lv, rng: random.Random, n: int) -> list[int]:
    """`P_NewChaseDir` on the real E1M1: a zombieman at a subsector centroid
    with a target somewhere else, for every starting `movedir`."""
    out: list[int] = []
    kind = KINDS["possessed"]
    moved = 0
    while len(out) < n * 12:
        mx, my, _ = phys.inside_point(lv, rng)
        tx, ty, _ = phys.inside_point(lv, rng)
        if (mx, my) == (tx, ty):
            continue
        olddir = rng.randrange(0, 9)
        seed = rng.randrange(0, 256)
        mo = Mon(lv, kind, mx, my)
        mo.move_dir = olddir
        target = Mon(lv, T["KIND_PLAYER"], tx, ty)
        r = Rng(seed)
        new_chase_dir(lv, mo, target, r, [mo, target])
        moved += int((mo.x, mo.y) != (mx, my))
        out.extend(
            [enc(mx), enc(my), enc(tx), enc(ty), olddir, seed,
             mo.move_dir, enc(mo.x), enc(mo.y), mo.move_count, r.index,
             int((mo.x, mo.y) != (mx, my))]
        )
    print("chasedirs: %d cases, %d of which actually stepped" % (n, moved))
    return out


def gen_missile_ranges(rng: random.Random, n: int) -> list[int]:
    """`P_CheckMissileRange`'s probability rule, sight and `MF_JUSTHIT`
    already decided by the caller: distance, melee, reaction time, RNG."""
    out: list[int] = []
    for _ in range(n):
        dist = rng.randrange(0, 1200 * FRACUNIT)
        has_melee = rng.randrange(0, 2)
        reaction = rng.randrange(0, 2) * 8
        seed = rng.randrange(0, 256)
        d = dist - 64 * FRACUNIT
        if not has_melee:
            d -= 128 * FRACUNIT
        d >>= 16
        if d > 200:
            d = 200
        r = Rng(seed)
        if reaction:
            verdict = 0
        else:
            verdict = int(not r.next() < d)
        out.extend([enc(dist), has_melee, reaction, seed, verdict, r.index])
    print("missile ranges: %d cases" % n)
    return out


def gen_melees(lv, rng: random.Random, n: int) -> list[int]:
    """`P_CheckMeleeRange`: the distance rule and the sight test, on pairs
    close enough for the first to be interesting."""
    out: list[int] = []
    hits = 0
    kind = KINDS["sergeant"]
    while len(out) < n * 9:
        mx, my, _ = phys.inside_point(lv, rng)
        dx = rng.randrange(-90 * FRACUNIT, 90 * FRACUNIT)
        dy = rng.randrange(-90 * FRACUNIT, 90 * FRACUNIT)
        tx, ty = mx + dx, my + dy
        if lv.cell_of(tx, ty) is None:
            continue
        mo = Mon(lv, kind, mx, my)
        target = Mon(lv, T["KIND_PLAYER"], tx, ty)
        dist = approx_distance(tx - mx, ty - my)
        near = dist < MELEERANGE - 20 * FRACUNIT + target.radius
        if near:
            visible, margin = phys.check_sight_exact(lv, mo.as_sight(), target.as_sight())
            if lv.reject(mo.sector, target.sector):
                visible = False
            elif margin is not None and abs(margin) < FRACUNIT // 8:
                continue
            verdict = int(visible)
        else:
            verdict = 0
        hits += verdict
        out.extend([enc(mx), enc(my), enc(mo.z), enc(tx), enc(ty), enc(target.z),
                    target.radius // FRACUNIT, mo.sector, verdict])
    print("melees: %d cases, %d in range and visible" % (n, hits))
    return out


def gen_looks(lv, rng: random.Random, n: int) -> list[int]:
    """`A_Look` through `P_LookForPlayers`: sight, and the 180-degree blind
    arc outside melee range. Pairs whose angle falls within a degree of the
    arc's edge are dropped (the model's `atan2` is not `tantoangle`)."""
    out: list[int] = []
    stats = [0, 0]
    dropped = 0
    kind = KINDS["possessed"]
    while len(out) < n * 9:
        mx, my, _ = phys.inside_point(lv, rng)
        if rng.random() < 0.6:
            # Bias toward pairs close enough to be a plausible wake-up.
            px = mx + rng.randrange(-400 * FRACUNIT, 400 * FRACUNIT)
            py = my + rng.randrange(-400 * FRACUNIT, 400 * FRACUNIT)
            if lv.cell_of(px, py) is None:
                continue
        else:
            px, py, _ = phys.inside_point(lv, rng)
        if (mx, my) == (px, py):
            continue
        s1, s2 = lv.sector_at(mx, my), lv.sector_at(px, py)
        rejected = lv.reject(s1, s2)
        if rejected and rng.random() < 0.8:
            continue
        angle = rng.randrange(0, 8) * ANG45
        mo = Mon(lv, kind, mx, my)
        mo.angle = angle
        player = Mon(lv, T["KIND_PLAYER"], px, py)
        if rejected:
            visible = False
        else:
            visible, margin = phys.check_sight_exact(lv, mo.as_sight(), player.as_sight())
            if margin is not None and abs(margin) < FRACUNIT // 8:
                dropped += 1
                continue
        verdict = 0
        if visible:
            an = (phys_point_to_angle(mx, my, px, py) - angle) & 0xFFFFFFFF
            edge = min(abs(an - ANG90), abs(an - ANG270))
            if edge < (1 << 32) // 360:
                dropped += 1
                continue
            if ANG90 < an < ANG270 and approx_distance(px - mx, py - my) > MELEERANGE:
                verdict = 0
            else:
                verdict = 1
        stats[verdict] += 1
        out.extend([enc(mx), enc(my), enc(mo.z), angle, enc(px), enc(py), enc(player.z),
                    int(visible), verdict])
    print("looks: %d cases (%d wake, %d do not), %d dropped for a thin margin"
          % (n, stats[1], stats[0], dropped))
    return out


CHASE_TICS = 300
CHASE_EVERY = 10


def gen_chase(lv, rng: random.Random) -> tuple[list[int], list[int]]:
    """A zombieman already awake, chasing a target it never gets to see.

    The point is to exercise `A_Chase`, `P_Move` and `P_NewChaseDir` for
    hundreds of tics against the real geometry without dragging the attacks
    (and their hitscans) into the model: as long as the sight test stays
    false, `A_Chase` can neither melee nor fire, so the trace is pure
    movement. The generator searches candidate pairs until it finds one that
    stays out of sight for the whole run, and emits the setup with the
    trace."""
    kind = KINDS["possessed"]
    for _ in range(4000):
        mx, my, _ = phys.inside_point(lv, rng)
        tx, ty, _ = phys.inside_point(lv, rng)
        if not lv.reject(lv.sector_at(mx, my), lv.sector_at(tx, ty)):
            continue
        if approx_distance(tx - mx, ty - my) < 400 * FRACUNIT:
            continue
        mo = Mon(lv, kind, mx, my)
        target = Mon(lv, T["KIND_PLAYER"], tx, ty)
        mo.target = 1
        mo.reaction_time = 0
        enter_state(mo, mi("seestate", kind))
        r = Rng(1)
        mobjs = [mo, target]
        trace: list[int] = []
        ok = True
        for tic in range(CHASE_TICS):
            if check_sight(lv, mo, target):
                ok = False
                break
            # `P_MobjThinker`: no momentum on a walker, so only the state
            # machine runs before the action.
            if mo.tics != FOREVER:
                if mo.tics > 1:
                    mo.tics -= 1
                    action = NO_ACTION
                else:
                    nxt = T["STATE_NEXT"][mo.state]
                    mo.state = nxt
                    mo.tics = T["STATE_TICS"][nxt]
                    action = T["STATE_ACTION"][nxt]
                if action == A_CHASE:
                    a_chase(lv, mo, mobjs, r, tic)
            if tic % CHASE_EVERY == CHASE_EVERY - 1:
                trace.extend([enc(mo.x), enc(mo.y), mo.move_dir, mo.move_count,
                              mo.state, mo.tics, r.index])
        if not ok:
            continue
        if approx_distance(mo.x - mx, mo.y - my) < 150 * FRACUNIT:
            continue  # the monster never got anywhere: not a useful trace
        setup = [enc(mx), enc(my), enc(tx), enc(ty)]
        print("chase: %d tics from (%.0f, %.0f) toward (%.0f, %.0f), ends at (%.0f, %.0f)"
              % (CHASE_TICS, mx / FRACUNIT, my / FRACUNIT, tx / FRACUNIT, ty / FRACUNIT,
                 (trace[-7] - BIAS) / FRACUNIT, (trace[-6] - BIAS) / FRACUNIT))
        return setup, trace
    raise SystemExit("no chase pair stayed out of sight for %d tics" % CHASE_TICS)


def gen_chains() -> list[int]:
    """The state walk of each kind, straight out of the generated tables:
    spawn -> see -> chase loop -> attack -> pain -> death, as the sequence of
    (state, tics, action) triples a `P_SetMobjState` chain visits."""
    out: list[int] = []
    for name in ("possessed", "shotguy", "troop", "sergeant", "shadows"):
        k = KINDS[name]
        for col in ("spawnstate", "seestate", "meleestate", "missilestate",
                    "painstate", "deathstate", "xdeathstate"):
            s = mi(col, k)
            out.extend([k, s, T["STATE_TICS"][s], T["STATE_ACTION"][s], T["STATE_NEXT"][s]])
    print("chains: %d rows" % (len(out) // 5))
    return out


# --------------------------------------------------------------------------
# Emission
# --------------------------------------------------------------------------

HEADER = """// SPDX-License-Identifier: GPL-2.0-only
//
//! GENERATED -- do not edit. Regenerate with
//! `python3 cairo/doom/doom_monsters/scripts/model.py --json <e1m1.json> --write`.
//!
//! Independent expectations for `src/tests/e1m1.cairo`, computed by the
//! Python reference model of `scripts/model.py` (a transcription of
//! `p_enemy.c`, over `doom_physics`' own geometry model) -- never from the
//! Cairo code. Coordinates are `fixed` offset-encoded (`enc = raw + 2^32`).
"""


def emit_array(name: str, ty: str, values: list[int], doc: str) -> str:
    body = ", ".join(str(v) for v in values)
    return "/// %s\npub const %s: [%s; %d] = [%s];\n\n" % (doc, name, ty, len(values), body)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--json", required=True)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--chasedirs", type=int, default=200)
    ap.add_argument("--missiles", type=int, default=150)
    ap.add_argument("--melees", type=int, default=80)
    ap.add_argument("--looks", type=int, default=150)
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    sys.setrecursionlimit(10000)
    lv = phys.Level(json.loads(Path(args.json).read_text()))
    rng = random.Random(args.seed)
    chasedirs = gen_chasedirs(lv, rng, args.chasedirs)
    missiles = gen_missile_ranges(rng, args.missiles)
    melees = gen_melees(lv, rng, args.melees)
    looks = gen_looks(lv, rng, args.looks)
    chains = gen_chains()
    setup, chase = gen_chase(lv, rng)

    text = HEADER + "\n"
    text += emit_array(
        "CHASEDIRS", "felt252", chasedirs,
        "12 felts per case: monster x, y; target x, y; olddir; RNG seed; then the "
        "expected movedir, x, y, movecount, RNG index and whether the monster stepped.",
    )
    text += emit_array(
        "MISSILE_RANGES", "felt252", missiles,
        "6 felts per case: distance, has-melee, reaction time, RNG seed, verdict, RNG index.",
    )
    text += emit_array(
        "MELEES", "felt252", melees,
        "9 felts per case: monster x, y, z; target x, y, z; target radius (units); "
        "monster sector; verdict.",
    )
    text += emit_array(
        "LOOKS", "felt252", looks,
        "9 felts per case: monster x, y, z; monster angle; player x, y, z; sight; wake.",
    )
    text += emit_array(
        "CHAINS", "felt252", chains,
        "5 felts per row: kind, state, tics, action, next state -- for the spawn, see, "
        "melee, missile, pain, death and gib entry of each of the five kinds.",
    )
    text += emit_array(
        "CHASE_SETUP", "felt252", setup,
        "The chase scenario: monster x, y and target x, y.",
    )
    text += "/// Tics of the chase scenario.\npub const CHASE_TICS: u32 = %d;\n\n" % CHASE_TICS
    text += "/// One checkpoint every this many tics.\npub const CHASE_EVERY: u32 = %d;\n\n" % CHASE_EVERY
    text += emit_array(
        "CHASE", "felt252", chase,
        "7 felts per checkpoint: x, y, movedir, movecount, state, tics, RNG index.",
    )
    if args.write:
        (CRATE / "src" / "tests").mkdir(parents=True, exist_ok=True)
        (CRATE / "src" / "tests" / "vectors.cairo").write_text(text)
        print("wrote src/tests/vectors.cairo")
    return 0


if __name__ == "__main__":
    sys.exit(main())
