#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the `bam` crate's trigonometric tables and their test vectors.

Two products, both committed:

1. `src/tables.cairo` -- the tables the crate actually uses, computed here
   from the closed-form formulas below and from nothing else (clean-room):

       FINESINE_Q[i] = trunc(sin((i + 0.5) * 2*pi / 8192) * 65536)
                       for i in 0 .. 2047            (one quarter wave)

       TANTOANGLE[i] = trunc(atan2(i, 2048) * 2^32 / (2*pi))
                       for i in 0 .. 2048

   The quarter wave is the whole table: the sampling `(i + 0.5)` makes the
   full 8192-entry sine exactly symmetric, `sin[i] = sin[4095 - i]` and
   `sin[i + 4096] = -sin[i]`, so 2048 magnitudes and two comparisons rebuild
   every entry (S1 §7: 8 191 felts saved, ~1 200 steps/tic amortized at
   K = 100, against ~15 steps per call to fold).

2. `src/tests/vectors.cairo` -- reference values sampled from Doom's own
   `finesine[]` / `tantoangle[]`, used only to *check* the generated tables.
   They are extracted from a `tables.c` taken from a doomgeneric or
   Chocolate Doom checkout, which is **never committed** (it is GPL-2.0); only
   the numeric samples are, as test vectors.

Usage:
    python3 scripts/gen_tables.py --write                 # tables only
    python3 scripts/gen_tables.py --write --tables-c PATH  # tables + vectors
"""

from __future__ import annotations

import argparse
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FINEANGLES = 8192
QUARTER = FINEANGLES // 4  # 2048
SLOPERANGE = 2048
ANG_FULL = 1 << 32


def finesine_q(i: int) -> int:
    """One quarter wave of Doom's `finesine`, as a non-negative magnitude."""
    return int(math.sin((i + 0.5) * 2 * math.pi / FINEANGLES) * 65536)


def finesine_full(i: int) -> int:
    """`finesine[i]` for i in 0 .. 8191, rebuilt from the quarter wave
    exactly the way the Cairo crate does."""
    j = i % FINEANGLES
    negative = j >= 4096
    if negative:
        j -= 4096
    if j >= QUARTER:
        j = 4095 - j
    m = finesine_q(j)
    return -m if negative else m


def tantoangle(i: int) -> int:
    return int(math.atan2(i, SLOPERANGE) * ANG_FULL / (2 * math.pi))


def emit(name: str, values: list[int], per_line: int = 8) -> str:
    body = ",\n    ".join(
        ", ".join(str(v) for v in values[i:i + per_line])
        for i in range(0, len(values), per_line)
    )
    return "pub const %s: [felt252; %d] = [\n    %s,\n];\n" % (name, len(values), body)


TABLES_HEADER = """// SPDX-License-Identifier: Apache-2.0
// GENERATED by scripts/gen_tables.py -- do not edit by hand.
//
//   FINESINE_Q[i] = trunc(sin((i + 0.5) * 2*pi / 8192) * 65536), i in 0..2047
//   TANTOANGLE[i] = trunc(atan2(i, 2048) * 2^32 / (2*pi)),       i in 0..2048
//
// FINESINE_Q holds one quarter wave as a non-negative magnitude; `sine()`
// rebuilds the full 8192-entry wave with two comparisons. Both tables are
// plain `const` arrays: S1 §5.1 measured a `Span` index at a constant 11
// steps whatever the array size, against 24 for a 16-way `if` tree, and
// §5.9 measured 1 word of bytecode per `const` felt against 18 per `if`.
"""

VECTORS_HEADER = """// SPDX-License-Identifier: Apache-2.0
// GENERATED by scripts/gen_tables.py --tables-c <path> -- do not edit.
//
// Reference values sampled from Doom's `finesine[]` and `tantoangle[]`
// (tables.c of a doomgeneric / Chocolate Doom checkout, GPL-2.0, never
// committed here). Only these numeric samples are committed, as test
// vectors for the tables this crate generates from closed-form formulas.
//
// Doom's tables were computed in the 1990s with limited floating-point
// precision, so they differ from the exact formulas by a few units in the
// last place. The measured deviations over the whole tables are:
//
//   finesine   : %(sin_bad)d / 10240 entries differ, all by exactly +/-1
//                (max |delta| = %(sin_max)d)
//   tantoangle : %(tan_bad)d / 2049 entries differ, max |delta| = %(tan_max)d BAM
//                (1 BAM = 8.4e-8 degrees)
//
// The tests therefore assert an exact match on the anchors and a bounded
// deviation elsewhere, and record the deviation counts above so that a
// regression in the generator shows up as a changed count.
//
// PTA_* are %(pta_n)d (dx, dy) vectors -- the degenerate one, the eight
// axis and diagonal directions at two magnitudes, and a pseudo-random
// sweep -- with the angle that a Python transcription of Doom's octant
// algorithm returns. That transcription is checked here, at generation
// time, against `atan2` on every point: the largest deviation is
// %(pta_max)d BAM (%(pta_deg).4f degrees), which is the granularity of the
// 2 049-entry `tantoangle` table, not an error of the port.
//
// The %(pta_tiny)d vectors shorter than 512 raw units (1/128 of a map unit)
// are excluded from that bound: Doom's `SlopeDiv` returns `SLOPERANGE`
// whenever the denominator is below 512, so those deltas legitimately
// answer "45 degrees into the octant". They are kept in the vectors
// precisely to pin that branch.
"""


ANG45 = ANG_FULL // 8
ANG90 = ANG_FULL // 4
ANG180 = ANG_FULL // 2
ANG270 = 3 * ANG_FULL // 4


def slope_div(num: int, den: int) -> int:
    """Doom's SlopeDiv, on two non-negative raw magnitudes."""
    if den < 512:
        return SLOPERANGE
    ans = (num << 3) // (den >> 8)
    return ans if ans <= SLOPERANGE else SLOPERANGE


def point_to_angle(x: int, y: int) -> int:
    """Doom's R_PointToAngle2 on raw 16.16 deltas, returning a BAM angle."""
    tan = tantoangle
    if x == 0 and y == 0:
        return 0
    if x >= 0:
        if y >= 0:
            if x > y:
                return tan(slope_div(y, x))
            return ANG90 - 1 - tan(slope_div(x, y))
        y = -y
        if x > y:
            return (-tan(slope_div(y, x))) % ANG_FULL
        return ANG270 + tan(slope_div(x, y))
    x = -x
    if y >= 0:
        if x > y:
            return ANG180 - 1 - tan(slope_div(y, x))
        return ANG90 + tan(slope_div(x, y))
    y = -y
    if x > y:
        return ANG180 + tan(slope_div(y, x))
    return ANG270 - 1 - tan(slope_div(x, y))


def angular_delta(a: int, b: int) -> int:
    """Shortest distance between two BAM angles."""
    d = (a - b) % ANG_FULL
    return min(d, ANG_FULL - d)


def pta_points(n: int) -> list[tuple[int, int]]:
    """Deterministic (dx, dy) raw pairs: the eight axis/diagonal directions
    and the degenerate vector first, then a pseudo-random sweep."""
    unit = 65536
    pts = [(0, 0)]
    for d in (1, 1024 * unit):
        pts += [(d, 0), (0, d), (-d, 0), (0, -d), (d, d), (-d, d), (d, -d), (-d, -d)]
    pts += [(unit, 3 * unit), (3 * unit, unit), (-unit, 3 * unit), (511, -512)]
    state = 0x5EED1234
    while len(pts) < n:
        state = (state * 6364136223846793005 + 1442695040888963407) % (1 << 64)
        dx = (state % (1 << 27)) - (1 << 26)
        state = (state * 6364136223846793005 + 1442695040888963407) % (1 << 64)
        dy = (state % (1 << 27)) - (1 << 26)
        pts.append((dx, dy))
    return pts


def build_pta_vectors(n: int = 1000) -> tuple[str, int, int, int]:
    pts = pta_points(n)
    worst = 0
    tiny = 0
    dxs, dys, angs = [], [], []
    for dx, dy in pts:
        a = point_to_angle(dx, dy)
        assert 0 <= a < ANG_FULL
        if (dx, dy) == (0, 0):
            pass
        elif max(abs(dx), abs(dy)) < 512:
            # SlopeDiv's own floor: Doom answers 45 degrees into the octant.
            tiny += 1
        else:
            exact = int(round(math.atan2(dy, dx) % (2 * math.pi) * ANG_FULL / (2 * math.pi)))
            worst = max(worst, angular_delta(a, exact % ANG_FULL))
        dxs.append(dx + (1 << 32))
        dys.append(dy + (1 << 32))
        angs.append(a)
    text = "/// Raw deltas in the `fixed` offset encoding (`enc = raw + 2^32`).\n"
    text += emit("PTA_DX_ENC", dxs) + "\n"
    text += emit("PTA_DY_ENC", dys) + "\n"
    text += "/// Largest deviation (BAM) between the vectors above and atan2,\n"
    text += "/// over the vectors at least 512 raw units long.\n"
    text += "pub const PTA_MAX_DELTA: felt252 = %d;\n\n" % worst
    text += "/// Angle returned by the Python transcription of R_PointToAngle2.\n"
    text += emit("PTA_ANGLE", angs)
    return text, len(pts), worst, tiny


def parse_tables_c(path: Path) -> dict[str, list[int]]:
    src = path.read_text(errors="replace")
    out = {}
    for name in ("finesine", "tantoangle"):
        m = re.search(r"\b" + name + r"\s*\[[^\]]*\]\s*=\s*\{(.*?)\};", src, re.S)
        if not m:
            raise SystemExit("could not find %s[] in %s" % (name, path))
        body = re.sub(r"//.*", "", m.group(1))
        out[name] = [int(t.strip(), 0) for t in body.split(",") if t.strip()]
    return out


def build_vectors(tables: dict[str, list[int]]) -> str:
    doom_sin = tables["finesine"]
    doom_tan = tables["tantoangle"]
    if len(doom_sin) != 10240 or len(doom_tan) != 2049:
        raise SystemExit("unexpected table sizes: %d, %d" % (len(doom_sin), len(doom_tan)))

    sin_deltas = [finesine_full(i) - doom_sin[i] for i in range(FINEANGLES)]
    # finesine[8192 .. 10239] is finecosine's tail: finesine[i] for i < 2048.
    tail = [finesine_full(i) - doom_sin[FINEANGLES + i] for i in range(2048)]
    sin_bad = sum(1 for d in sin_deltas + tail if d) or 0
    sin_max = max(abs(d) for d in sin_deltas + tail)
    tan_deltas = [tantoangle(i) - doom_tan[i] for i in range(2049)]
    tan_bad = sum(1 for d in tan_deltas if d)
    tan_max = max(abs(d) for d in tan_deltas)

    # Sample every 53rd entry (coprime with 8192 and 2049, so the sample walks
    # the whole table) plus the anchors that must match exactly.
    sin_idx = sorted(set(list(range(0, FINEANGLES, 53)) + [0, 1, 2047, 2048, 4095, 4096, 8191]))
    tan_idx = sorted(set(list(range(0, 2049, 23)) + [0, 1, 2047, 2048]))

    pta_text, pta_n, pta_max, pta_tiny = build_pta_vectors()
    text = VECTORS_HEADER % dict(sin_bad=sin_bad, sin_max=sin_max,
                                 tan_bad=tan_bad, tan_max=tan_max,
                                 pta_n=pta_n, pta_max=pta_max, pta_tiny=pta_tiny,
                                 pta_deg=pta_max * 360.0 / ANG_FULL)
    text += "\n/// Number of `finesine` entries (out of 10 240) where Doom's table and\n"
    text += "/// the generated one differ, and the largest deviation.\n"
    text += "pub const FINESINE_DEVIATIONS: u32 = %d;\n" % sin_bad
    text += "pub const FINESINE_MAX_DELTA: felt252 = %d;\n\n" % sin_max
    text += "/// Same for `tantoangle` (out of 2 049), in BAM units.\n"
    text += "pub const TANTOANGLE_DEVIATIONS: u32 = %d;\n" % tan_bad
    text += "pub const TANTOANGLE_MAX_DELTA: felt252 = %d;\n\n" % tan_max
    text += emit("SIN_INDEX", sin_idx) + "\n"
    # Doom values are signed; store them offset by 65536 to keep every
    # committed constant a non-negative felt, like the crate's own encoding.
    text += "/// Doom's `finesine[SIN_INDEX[k]]`, offset by +65536 to stay non-negative.\n"
    text += emit("SIN_DOOM_OFFSET", [doom_sin[i] + 65536 for i in sin_idx]) + "\n"
    text += emit("TAN_INDEX", tan_idx) + "\n"
    text += "/// Doom's `tantoangle[TAN_INDEX[k]]` (already non-negative).\n"
    text += emit("TAN_DOOM", [doom_tan[i] for i in tan_idx]) + "\n"
    text += pta_text
    return text


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--tables-c", type=Path, default=None,
                    help="path to a scratch copy of Doom's tables.c (never committed)")
    args = ap.parse_args()

    q = [finesine_q(i) for i in range(QUARTER)]
    t = [tantoangle(i) for i in range(SLOPERANGE + 1)]
    assert all(0 <= v <= 65535 for v in q), "quarter wave must be a 16-bit magnitude"
    assert t[0] == 0 and t[SLOPERANGE] == ANG_FULL // 8, "tantoangle anchors"
    assert all(0 <= v < ANG_FULL for v in t)

    tables = TABLES_HEADER + "\n" + emit("FINESINE_Q", q) + "\n" + emit("TANTOANGLE", t)
    if args.write:
        (ROOT / "src" / "tables.cairo").write_text(tables)
        print("wrote src/tables.cairo (%d + %d entries)" % (len(q), len(t)), file=sys.stderr)
    else:
        sys.stdout.write(tables)

    if args.tables_c is not None:
        vectors = build_vectors(parse_tables_c(args.tables_c))
        if args.write:
            out = ROOT / "src" / "tests" / "vectors.cairo"
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(vectors)
            print("wrote src/tests/vectors.cairo", file=sys.stderr)
        else:
            sys.stdout.write(vectors)
    return 0


if __name__ == "__main__":
    sys.exit(main())
