#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Hellproof contributors
# SPDX-License-Identifier: GPL-2.0-only
"""Copy only pinned BM_ITEMS into this experiment and pack six 11-bit ids/felt."""
import hashlib
from pathlib import Path
import re

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parents[1] / 'cairo/doom/doom_map/src/levels/e1m1.cairo'
text = SOURCE.read_text()
m = re.search(r'pub const BM_ITEMS: \[u32; 2064\] = \[(.*?)\];', text, re.S)
assert m
values = [int(x.strip(), 0) for x in m[1].split(',') if x.strip()]
assert len(values) == 2064 and max(values) < 2048
packed = [sum(value << (11 * j) for j, value in enumerate(values[i:i + 6])) for i in range(0, len(values), 6)]
assert len(packed) == 344 and all(x < 2**66 for x in packed)
header = '// SPDX-FileCopyrightText: 2026 Hellproof contributors\n// SPDX-License-Identifier: GPL-2.0-only\n'
header += '// Derived verbatim from cairo/doom/doom_map/src/levels/e1m1.cairo BM_ITEMS.\n'
header += '// Source SHA-256: ' + hashlib.sha256(SOURCE.read_bytes()).hexdigest() + '\n'
header += '// Generated by spikes/s13-map-packing/prepare.py; experimental data only.\n'
def emit(name, kind, data):
    rows = [', '.join(map(str, data[i:i + 8])) + ',' for i in range(0, len(data), 8)]
    return f'pub const {name}: [{kind}; {len(data)}] = [\n' + ''.join('    ' + row + '\n' for row in rows) + '];\n'
(HERE / 'src/data.cairo').write_text(header + emit('BM_ITEMS', 'u32', values) + '\n' + emit('BM_ITEMS_PACKED', 'u128', packed))
