//! Deterministic 256-entry RNG table, indexed exactly like Doom's P_Random.
//!
//! The table VALUES are generated by a documented LCG in the extractor, not
//! copied from linuxdoom's `rndtable` (licensing, see docs/spikes/S1.md).  The
//! step cost is identical: one increment, one wrap test, one const-array read.

use crate::tables::RNDTABLE;

/// Returns (new index, value in 0..255).
#[inline(always)]
pub fn p_random(idx: u32) -> (u32, u32) {
    let i = if idx == 255 {
        0
    } else {
        idx + 1
    };
    let v: felt252 = *RNDTABLE.span().at(i);
    let vu: u32 = v.try_into().unwrap();
    (i, vu)
}
